// Traduzioni inglesi dell'app: chiave = testo italiano (vedi src/i18n.js)
// File generato: si aggiorna insieme ai testi dell'app.
const D = {
"Accesso e installazione": "Access and installation",
"Primo accesso": "First access",
"Apri Chrome o Safari sul telefono o PC": "Open Chrome or Safari on your phone or PC",
"Vai su www.podereverdeapp.it": "Go to www.podereverdeapp.it",
"Tocca 'Registrati' → inserisci nome, email, password → 'Crea account'": "Tap 'Sign up' → enter name, email, password → 'Create account'",
"Accedi subito — nessuna conferma email necessaria": "Sign in straight away — no email confirmation needed",
"Installa sul telefono (accesso rapido senza browser)": "Install on your phone (quick access without the browser)",
"Android — Chrome: menu ⋮ → 'Aggiungi a schermata Home'": "Android — Chrome: menu ⋮ → 'Add to Home screen'",
"iPhone — Safari: icona 📤 → 'Aggiungi a schermata Home'": "iPhone — Safari: 📤 icon → 'Add to Home Screen'",
"Tutti i dati vengono salvati automaticamente nel database condiviso. Ogni operatore vede gli stessi dati in tempo reale da qualsiasi dispositivo. ⚠️ Usa sempre il browser in modalità normale (non in incognito) per restare connesso.": "All data is saved automatically in the shared database. Every operator sees the same data in real time from any device. ⚠️ Always use the browser in normal mode (not incognito) to stay signed in.",
"Navigazione — tutti i moduli": "Navigation — all modules",
"In basso ci sono i pulsanti per le sezioni principali. Scorri la barra per vederli tutti.": "At the bottom are the buttons for the main sections. Scroll the bar to see them all.",
"🐄 Gestione": "🐄 Management",
"Anagrafica animali, sanitario, alimentazione, magazzino, report, riproduttori": "Animal registry, health, feeding, store, reports, breeders",
"🧬 Pedigree": "🧬 Pedigree",
"Albero genealogico, consanguineità, prevenzione accoppiamenti a rischio": "Family tree, inbreeding, prevention of risky matings",
"🐷 Lotti": "🐷 Batches",
"Lotti suini (nati e acquistati) con tatuaggio automatico": "Pig batches (born on the farm and bought) with automatic tattoo",
"🌾 Coltivazione": "🌾 Crops",
"I campi aziendali: colture, semine, lavorazioni, raccolta, programma, costi, report e storico": "The farm fields: crops, sowing, field operations, harvest, plan, costs, reports and history",
"🏆 Selezione": "🏆 Selection",
"Ranking genetico: IIP, produttività, età primo parto, resa media figli": "Genetic ranking: calving interval, productivity, age at first birth, average yield of offspring",
"📤 Uscite": "📤 Exits",
"Macellazioni, vendite, morti — con resa % e IPG": "Slaughter, sales, deaths — with yield % and daily weight gain",
"🐾 UBA": "🐾 LU",
"Calcolo UBA medio per fascia di età con ripartizione presenza effettiva": "Average livestock units by age band, split by actual presence",
"📥 Esporta": "📥 Export",
"Export Excel granulare — anagrafica, uscite, UBA, consanguineità": "Detailed Excel export — registry, exits, livestock units, inbreeding",
"📮 Email": "📮 Email",
"Destinatari e invio automatico mensile di report e backup": "Recipients and automatic monthly sending of reports and backups",
"📖 Guida": "📖 Guide",
"Questo manuale": "This manual",
"Le vecchie tab 📊 Costi, 🧾 Origine e 🏭 Struttura non sono più nella barra: i costi per animale si consultano ora direttamente nella scheda dell'animale (tab 💰 Costi), e il grosso dell'analisi economica è passato al programma di Contabilità Industriale. I dati non sono stati cancellati.": "The old tabs 📊 Costs, 🧾 Origin and 🏭 Structure are no longer in the bar: costs per animal are now shown directly in the animal's record (💰 Costs tab), and most of the economic analysis has moved to the Cost Accounting program. No data has been deleted.",
"Scheda animale — cercare, consultare, modificare": "Animal record — search, view, edit",
"Trovare un animale": "Finding an animal",
"Vai in 🐄 Gestione → tab 🏷️ Animali": "Go to 🐄 Management → 🏷️ Animals tab",
"Usa la barra di ricerca: digita BDN completo, ultime 4 cifre del codice, nome o razza": "Use the search bar: type the full BDN code, the last 4 digits of the code, the name or the breed",
"Usa i filtri specie (bovino / suino / ovino) e 'Solo attivi'": "Use the species filters (cattle / pig / sheep) and 'Active only'",
"Aprire la scheda": "Opening the record",
"Tocca il pulsante colorato '📋 Apri scheda completa' su ogni card. La scheda ha 5 tab:": "Tap the coloured button '📋 Open full record' on each card. The record has 5 tabs:",
"📋 Info": "📋 Info",
"BDN, razza, sesso, nascita, pesi, provenienza, azienda origine, prezzo acquisto, costo nascita, stato, vaccinazioni ricevute": "BDN, breed, sex, birth, weights, origin, farm of origin, purchase price, birth cost, status, vaccinations received",
"🧬 Genealogia": "🧬 Family tree",
"Padre, madre, discendenti diretti — cliccabili": "Father, mother, direct offspring — all clickable",
"📅 Eventi": "📅 Events",
"Timeline di tutto: nascita, ingresso, parti, eventi sanitari, uscita": "Timeline of everything: birth, arrival, births given, health events, exit",
"💰 Costi": "💰 Costs",
"Costi anno per anno calcolati dalla Contabilità Industriale — sola lettura": "Costs year by year calculated by Cost Accounting — read only",
"⚖️ Pesate": "⚖️ Weighings",
"Storico di tutte le pesate dell'animale nel tempo": "History of all the animal's weighings over time",
"Modificare i dati": "Editing the data",
"Dalla scheda tocca ✏️ in alto a destra → modifica quello che vuoi → Salva.": "In the record tap ✏️ at the top right → change what you need → Save.",
"Registrare un nuovo animale": "Registering a new animal",
"Tocca '+ Aggiungi' in cima alla lista": "Tap '+ Add' at the top of the list",
"Seleziona SPECIE — i campi cambiano per bovino / suino / ovino": "Select the SPECIES — the fields change for cattle / pig / sheep",
"Inserisci BDN / Matricola, nome (facoltativo), razza, categoria, sesso, data nascita": "Enter BDN / ID number, name (optional), breed, category, sex, date of birth",
"Per acquistati: provenienza 'Acquistato' → compilare prezzo acquisto e azienda di origine": "For bought animals: origin 'Bought' → fill in purchase price and farm of origin",
"Per maschi destinati alla riproduzione: attiva il toggle '♂ Riproduttore'": "For males kept for breeding: switch on '♂ Breeder'",
"Collega padre e madre dalla lista per la genealogia": "Link father and mother from the list, for the family tree",
"La razza del figlio viene calcolata: stessa razza → pura; razze diverse → METICCIA": "The offspring's breed is calculated: same breed → purebred; different breeds → CROSSBRED",
"Tocca Salva": "Tap Save",
"Registro riproduttori": "Breeders register",
"Registrare un maschio come riproduttore": "Registering a male as a breeder",
"Cerca il maschio nella lista Animali": "Find the male in the Animals list",
"Apri la scheda → ✏️ Modifica": "Open the record → ✏️ Edit",
"Attiva il toggle '♂ Riproduttore' (compare solo per i maschi)": "Switch on '♂ Breeder' (it appears only for males)",
"Salva": "Save",
"Consultare il registro riproduttori": "Viewing the breeders register",
"In cima alla lista Animali tocca '♂ Riproduttori'. Vedi tutti i maschi registrati divisi per specie con nome, razza, età e numero di figli già registrati. Tocca una card per aprire la scheda.": "At the top of the Animals list tap '♂ Breeders'. You see all registered males by species with name, breed, age and number of offspring already registered. Tap a card to open the record.",
"Nel form parto, il campo 'Padre' mostra SOLO i maschi registrati come riproduttori della stessa specie. Se non ne hai ancora, mostra tutti i maschi come alternativa.": "In the birth form, the 'Father' field shows ONLY the males registered as breeders of the same species. If there are none yet, it shows all males instead.",
"⚠️ Cambiato: i maschi NON nascono più riproduttori": "⚠️ Changed: males are NO longer breeders from birth",
"Fino all'estate 2026 ogni maschio veniva marcato riproduttore automaticamente alla nascita, solo perché maschio. Era sbagliato e gonfiava il registro. Da settembre 2026 un maschio nasce NON riproduttore: lo diventa solo quando qualcuno attiva a mano il toggle '♂ Riproduttore' nella sua scheda.": "Until summer 2026 every male was automatically marked as a breeder at birth, just because it was male. That was wrong and inflated the register. Since September 2026 a male is born NOT a breeder: it becomes one only when someone switches on '♂ Breeder' by hand in its record.",
"Le femmine restano invece automatiche: diventano riproduttrici al primo parto registrato": "Females are still automatic: they become breeders at their first registered birth",
"Dalla data in cui attivi il toggle, l'app registra anche la data di qualifica, che compare nella timeline del tab 📅 Eventi": "From the day you switch it on, the app also records the qualification date, which appears in the timeline of the 📅 Events tab",
"Se un vecchio maschio risulta riproduttore per sbaglio, apri la scheda, Modifica, e spegni il toggle": "If an old male is wrongly shown as a breeder, open the record, Edit, and switch it off",
"Registrare un parto (bovini e ovini)": "Registering a birth (cattle and sheep)",
"Nuovo parto (crea schede figli)": "New birth (creates the offspring records)",
"Apri la scheda della MADRE": "Open the MOTHER's record",
"Tab '📅 Eventi' → '🐣 Nuovo parto'": "'📅 Events' tab → '🐣 New birth'",
"Inserisci data, tipo parto, N° nati TOTALI e N° nati morti": "Enter date, type of birth, TOTAL number born and number born dead",
"I nati vivi sono calcolati automaticamente (totali − morti)": "Live births are calculated automatically (total − dead)",
"Seleziona il padre dalla lista riproduttori": "Select the father from the breeders list",
"Per ogni nato vivo: BDN, sesso, peso nascita": "For each live newborn: BDN, sex, birth weight",
"Tocca 'Registra parto'": "Tap 'Register birth'",
"Le schede dei nati vengono create AUTOMATICAMENTE con razza calcolata, madre, padre, data nascita e provenienza 'Nato in azienda'.": "The newborns' records are created AUTOMATICALLY with calculated breed, mother, father, date of birth and origin 'Born on the farm'.",
"Parto storico (solo statistiche)": "Past birth (statistics only)",
"Tocca '📅 Parto storico'": "Tap '📅 Past birth'",
"Inserisci: data, nati totali, nati morti": "Enter: date, total born, born dead",
"Nessun BDN richiesto — utile per parti già avvenuti con figli non in azienda": "No BDN needed — useful for past births whose offspring are not on the farm",
"Alimenta automaticamente la Selezione Genetica per il calcolo IIP": "Automatically feeds Genetic Selection for the calving interval",
"Modificare o eliminare un parto": "Editing or deleting a birth",
"Nel tab 📅 Eventi: ogni parto mostra ✏️ (modifica dati) e 🗑️ (elimina evento). La modifica aggiorna solo i dati statistici — le schede dei figli già creati non vengono toccate.": "In the 📅 Events tab every birth shows ✏️ (edit data) and 🗑️ (delete event). Editing changes only the statistical data — the offspring records already created are not touched.",
"Gestione parto e lotti suini": "Farrowing and pig batches",
"Identificazione suini — due sistemi normativi": "Pig identification — two legal systems",
"Matricola individuale": "Individual ID number",
"Razze pregiate (Cinta Senese, Nero Apucalabro, Mora Romagnola, Nero Casertano) e riproduttori (verri e scrofe)": "Valuable breeds (Cinta Senese, Nero Apucalabro, Mora Romagnola, Nero Casertano) and breeders (boars and sows)",
"Codice lotto (tatuaggio)": "Batch code (tattoo)",
"Animali da ingrasso — tutti i suinetti di un parto portano lo stesso numero tatuato sull'orecchio": "Fattening animals — all the piglets of one farrowing carry the same number tattooed on the ear",
"Codice lotto — come viene generato": "Batch code — how it is generated",
"Il codice è composto da: AA (anno) + MM (mese) + lettera razza madre + lettera razza padre + ultime 2 cifre matricola madre.": "The code is made of: YY (year) + MM (month) + letter of the mother's breed + letter of the father's breed + last 2 digits of the mother's ID number.",
"Nero Apucalabro": "Nero Apucalabro",
"Cinta Senese": "Cinta Senese",
"Duroc": "Duroc",
"Mora Romagnola": "Mora Romagnola",
"Large White": "Large White",
"Meticcio": "Crossbred",
"Nero Casertano": "Nero Casertano",
"Landrace": "Landrace",
"Altra": "Other",
"Esempio: madre Cinta Senese matricola 392019 + padre Cinta Senese + parto 22/04/2023 → codice lotto 2304CC19. Unità: 2304CC1901, 2304CC1902, ...": "Example: Cinta Senese mother ID 392019 + Cinta Senese father + farrowing 22/04/2023 → batch code 2304CC19. Units: 2304CC1901, 2304CC1902, ...",
"Registrare un parto suini dalla sezione Lotti": "Registering a farrowing from the Batches section",
"Vai in 🐷 Lotti → '+ Nuovo parto'": "Go to 🐷 Batches → '+ New farrowing'",
"Scegli madre e padre → il codice lotto appare subito automaticamente": "Choose mother and father → the batch code appears at once",
"Inserisci data parto, nati totali, nati morti → i vivi si calcolano": "Enter farrowing date, total born, born dead → live ones are calculated",
"Facoltativo: data accoppiamento → calcola data prevista parto (+3 mesi +3 sett. +3 giorni)": "Optional: mating date → calculates the expected farrowing date (+3 months +3 weeks +3 days)",
"Tocca 'Registra parto e crea lotto'": "Tap 'Register farrowing and create batch'",
"L'app crea il lotto + N unità (una per ogni nato vivo) + evento riproduttivo sulla madre": "The app creates the batch + N units (one for each live piglet) + a reproductive event on the mother",
"Gestire le unità di un lotto": "Managing the units of a batch",
"Tocca un lotto nella lista → si apre la scheda con tutte le unità": "Tap a batch in the list → its record opens with all the units",
"Cerca per tatuaggio completo (es. 2304CC1901) o parziale": "Search by full tattoo (e.g. 2304CC1901) or part of it",
"Su ogni unità (✏️): assegna sesso, destinazione (ingrasso / riproduzione / macello), matricola individuale": "On each unit (✏️): set sex, destination (fattening / breeding / slaughter), individual ID number",
"Pulsante 📤 per registrare uscita: motivo, data, peso vivo, peso carcassa, resa % calcolata": "📤 button to register an exit: reason, date, live weight, carcass weight, calculated yield %",
"La scheda lotto mostra in sintesi: vivi / macellati / deceduti / riproduttori / maschi / femmine": "The batch record shows a summary: alive / slaughtered / dead / breeders / males / females",
"Trovare un suinetto per tatuaggio": "Finding a piglet by tattoo",
"Nella lista lotti: usa la barra di ricerca in cima — digita il tatuaggio completo (es. 2304CC1901) o il codice lotto (es. 2304CC19) per trovare subito l'unità.": "In the batches list use the search bar at the top — type the full tattoo (e.g. 2304CC1901) or the batch code (e.g. 2304CC19) to find the unit at once.",
"Registro sanitario": "Health register",
"Tre modalità di registrazione": "Three ways to register",
"+ Singolo": "+ Single",
"Un singolo animale — apri, compila, salva": "One single animal — open, fill in, save",
"💉 Gruppo": "💉 Group",
"Più animali dell'anagrafica (bovini, ovini, suini con matricola) — selezione multipla con spunte": "Several animals from the registry (cattle, sheep, pigs with ID number) — multiple selection with ticks",
"🐷 Lotto": "🐷 Batch",
"Suinetti di un lotto specifico — selezione per lotto poi per unità": "Piglets of a specific batch — choose the batch, then the units",
"Evento di gruppo": "Group event",
"Tocca '💉 Gruppo'": "Tap '💉 Group'",
"STEP 1: seleziona gli animali con le spunte (cerca per BDN, ultime 4 cifre o nome)": "STEP 1: select the animals with the ticks (search by BDN, last 4 digits or name)",
"Usa 'Seleziona tutti' per trattare l'intera mandria": "Use 'Select all' to treat the whole herd",
"STEP 2: compila tipo, descrizione, prodotto, veterinario, data, costo totale": "STEP 2: fill in type, description, product, vet, date, total cost",
"Il costo viene diviso automaticamente per il numero di animali": "The cost is divided automatically by the number of animals",
"Tocca 'Registra evento su N animali'": "Tap 'Register event on N animals'",
"Trattamento su lotto suini": "Treatment on a pig batch",
"Tocca '🐷 Lotto'": "Tap '🐷 Batch'",
"STEP 1: scegli il lotto dalla lista (cerca per codice lotto)": "STEP 1: choose the batch from the list (search by batch code)",
"Seleziona le unità da trattare (o 'Seleziona tutte le vive')": "Select the units to treat (or 'Select all alive')",
"STEP 2: compila i dati del trattamento": "STEP 2: fill in the treatment data",
"Tocca 'Registra trattamento su N unità'": "Tap 'Register treatment on N units'",
"Ricerca eventi": "Searching events",
"Usa la barra di ricerca in cima: cerca per BDN, ultime 4 cifre, nome animale, tipo evento o prodotto farmaceutico.": "Use the search bar at the top: search by BDN, last 4 digits, animal name, event type or medicine.",
"Le vaccinazioni compaiono automaticamente nella scheda di ogni animale (tab 📋 Info → sezione Vaccinazioni).": "Vaccinations appear automatically in each animal's record (📋 Info tab → Vaccinations section).",
"Alimentazione": "Feeding",
"Due modalità": "Two ways",
"Razione per un singolo animale o specie": "Ration for a single animal or species",
"🌾 Gruppo": "🌾 Group",
"Stessa razione su più animali con selezione multipla": "Same ration on several animals with multiple selection",
"Razione di gruppo": "Group ration",
"Tocca '🌾 Gruppo'": "Tap '🌾 Group'",
"STEP 1: seleziona gli animali": "STEP 1: select the animals",
"STEP 2: tipo mangime, quantità PER CAPO, unità, data, costo totale": "STEP 2: feed type, quantity PER HEAD, unit, date, total cost",
"Il costo viene diviso per i capi — vedi anteprima quantità totale (es. 3 kg × 45 = 135 kg)": "The cost is divided by the number of head — see the total quantity preview (e.g. 3 kg × 45 = 135 kg)",
"Tocca 'Registra razione su N animali'": "Tap 'Register ration on N animals'",
"Pesate — lo storico dei pesi": "Weighings — the weight history",
"Prima c'era un solo campo 'peso attuale' che si sovrascriveva a ogni aggiornamento: della pesata precedente non restava traccia. Ora ogni pesata è una riga a sé, e la storia dell'animale resta tutta.": "Before, there was a single 'current weight' field that was overwritten at every update: nothing remained of the previous weighing. Now every weighing is a row of its own, and the animal's whole history is kept.",
"Registrare una pesata": "Registering a weighing",
"Apri la scheda dell'animale → tab ⚖️ Pesate": "Open the animal's record → ⚖️ Weighings tab",
"Tocca '+ Registra pesata'": "Tap '+ Register weighing'",
"Inserisci data e peso in kg": "Enter date and weight in kg",
"Scegli il tipo di rilevazione (vedi tabella sotto)": "Choose the type of measurement (see the table below)",
"Salva — la riga compare nell'elenco, eliminabile con 🗑️ se hai sbagliato": "Save — the row appears in the list; you can delete it with 🗑️ if you made a mistake",
"I tipi di rilevazione": "Types of measurement",
"Nascita": "Birth",
"Peso alla nascita": "Weight at birth",
"Ingresso": "Arrival",
"Peso rilevato quando l'animale entra in azienda — importante per gli acquistati, di cui non conosciamo il peso di nascita vero": "Weight taken when the animal arrives on the farm — important for bought animals, whose real birth weight we don't know",
"In vita": "Alive",
"Una pesata qualsiasi durante l'allevamento": "Any weighing during rearing",
"Uscita vivo": "Exit alive",
"Peso vivo al momento dell'uscita": "Live weight at the moment of exit",
"Uscita carcassa": "Exit carcass",
"Peso della carcassa dal referto del macello": "Carcass weight from the slaughterhouse report",
"La spunta 'stimato'": "The 'estimated' tick",
"Serve a distinguere un peso REALE da uno messo per convenzione. Quando un animale è stato acquistato e il peso di nascita non si conosce, si usa lo standard di specie (45 kg bovino, 0,5 kg suino, 2 kg ovino) e si spunta 'stimato'. Così chi legge i dati sa che quel numero non è stato misurato.": "It tells a REAL weight apart from one entered by convention. When an animal was bought and its birth weight is unknown, the species standard is used (45 kg cattle, 0.5 kg pig, 2 kg sheep) and 'estimated' is ticked. So whoever reads the data knows that number was not measured.",
"Perché ha senso pesare spesso: la Contabilità Industriale userà tutti questi punti data/peso per stimare l'accrescimento e il costo al kg per fascia di età. Più pesate reali ci sono, più quella stima è affidabile — e i pesi si accumulano solo se qualcuno li registra.": "Why it makes sense to weigh often: Cost Accounting will use all these date/weight points to estimate growth and the cost per kg by age band. The more real weighings there are, the more reliable that estimate is — and weights build up only if someone records them.",
"Coltivazione — campi, colture, costi e report": "Crops — fields, crops, costs and reports",
"La sezione 🌾 Coltivazione raccoglie i campi aziendali (16 in uso oggi, 84,43 ettari, più quelli coltivati negli anni passati) con foto aerea e dati catastali, e tutto quello che ci si fa sopra campagna per campagna: colture, semine, lavorazioni, concimi, raccolte, costi e risultati.": "The 🌾 Crops section holds the farm fields (16 in use today, 84.43 hectares, plus those farmed in past years) with aerial photo and land-registry data, and everything done on them season by season: crops, sowing, field operations, fertilisers, harvests, costs and results.",
"La campagna agraria — si sceglie in cima": "The farming season — chosen at the top",
"Il selettore in alto comanda l'intera sezione: cambiando campagna cambia tutto quello che vedi sotto. La campagna va dal 1° settembre al 31 agosto: la semina d'autunno e la trebbiatura dell'estate dopo stanno nella stessa campagna, e anche le semine di primavera-estate (pascoli, erbai in irriguo) appartengono alla campagna iniziata il settembre precedente. Si arriva indietro fino al 2019/2020; la 2022/2023 non è caricata.": "The selector at the top controls the whole section: changing the season changes everything you see below. The season runs from 1 September to 31 August: autumn sowing and the following summer's threshing are in the same season, and spring-summer sowings too (pastures, irrigated forage crops) belong to the season that started the previous September. You can go back to 2019/2020; 2022/2023 is not loaded.",
"Le cinque linguette": "The five tabs",
"🗺️ Campi": "🗺️ Fields",
"Lista dei campi e scheda di ogni campo: si registra qui": "List of fields and record of each field: this is where you register",
"📊 Riepilogo": "📊 Summary",
"Ettari, giornate di lavoro, quantità e rese della campagna, per coltura": "Hectares, working days, quantities and yields of the season, by crop",
"🗓️ Programma": "🗓️ Plan",
"Cosa seminare e concimare in ogni campo, e cosa comprare": "What to sow and fertilise in each field, and what to buy",
"📈 Report": "📈 Report",
"Costi, valore di mercato e rese della campagna scelta": "Costs, market value and yields of the chosen season",
"📚 Storico": "📚 History",
"Tutte le stagioni insieme: per coltura, per campo e classifiche": "All seasons together: by crop, by field and rankings",
"🗺️ Campi — la scheda del campo": "🗺️ Fields — the field record",
"Tocca un campo: si apre la scheda con le colture della campagna": "Tap a field: its record opens with the crops of the season",
"Per metterne una nuova tocca '+ Aggiungi coltura' e scegli fra Avena, Erba Medica, Erbaio Misto, Grano, Orzo, Pisello Proteico, Produzione Seme, Sulla — oppure 'Altro' e scrivi il nome": "To add a new one tap '+ Add crop' and choose among Oats, Alfalfa, Mixed forage crop, Wheat, Barley, Protein pea, Seed production, Sulla — or 'Other' and type the name",
"Per medica e sulla, che sono poliennali, indica in quale campagna sono state seminate: nelle campagne dopo la semina non viene più chiesta": "For alfalfa and sulla, which are perennial, enter the season in which they were sown: in the following seasons sowing is no longer asked",
"Salva — compare il blocco della coltura con tre linguette: Semina, Lavorazioni, Raccolta": "Save — the crop block appears with three tabs: Sowing, Field operations, Harvest",
"Sullo stesso campo puoi mettere PIÙ colture nella stessa campagna: le successioni (orzo mietuto a giugno e poi un erbaio estivo, o il sorgo dopo il pascolo) e le porzioni di campo con colture diverse. Basta premere di nuovo '+ Aggiungi coltura'.": "On the same field you can put SEVERAL crops in the same season: successions (barley cut in June and then a summer forage crop, or sorghum after grazing) and parts of a field with different crops. Just tap '+ Add crop' again.",
"🌱 Semina": "🌱 Sowing",
"Nel menu 'Seme' compaiono per primi, con 📋, i semi previsti dal Programma per quella coltura; sotto, tutti i semi già usati in azienda. Se manca, scegli '✏️ Altro seme' e scrivi il nome": "In the 'Seed' menu the seeds planned in the Plan for that crop come first, marked 📋; below them, all seeds already used on the farm. If one is missing, choose '✏️ Other seed' and type the name",
"Inserisci la quantità in quintali: l'app calcola da sola i chilogrammi, i quintali per ettaro e i chilogrammi per ettaro sugli ettari della coltura": "Enter the quantity in quintals (1 quintal = 100 kg): the app calculates by itself the kilograms, quintals per hectare and kilograms per hectare on the crop's hectares",
"Per GRANO e ORZO puoi usare le 'dosi' (confezioni) al posto dei quintali: in quel caso calcola le dosi per ettaro": "For WHEAT and BARLEY you can use 'doses' (bags) instead of quintals: in that case it calculates doses per hectare",
"Per ERBAIO MISTO e PRODUZIONE SEME registra una riga per ciascuna essenza (trifoglio, avena, loietto) con '+ Aggiungi seme'": "For MIXED FORAGE CROP and SEED PRODUCTION register one row for each species (clover, oats, ryegrass) with '+ Add seed'",
"🚜 Lavorazioni": "🚜 Field operations",
"L'elenco delle 15 lavorazioni è sempre lì: aratura, estirpatura, erpicatura, morganatura, rippatura, spietratura, concimazione, semina, disserbo, sfalcio, ranghinatura, pressatura balle, raccolta balle, trebbiatura, irrigazione.": "The list of the 15 field operations is always there: ploughing, cultivating, harrowing, disc harrowing, ripping, stone removal, fertilising, sowing, weeding, mowing, raking, baling, bale collection, threshing, irrigation.",
"Tocca la riga della lavorazione eseguita — si apre": "Tap the row of the operation carried out — it opens",
"Tocca 'Registra esecuzione'": "Tap 'Register execution'",
"Metti la data e le giornate di lavoro impiegate — anche mezze giornate, si scrive 0,5": "Enter the date and the working days used — half days too, written 0.5",
"Salva: la spunta della riga diventa verde": "Save: the row's tick turns green",
"La stessa lavorazione si registra più volte: la medica si sfalcia 3-4 volte l'anno e l'irrigazione si ripete per tutta l'estate. Ogni volta aggiungi una nuova esecuzione con la sua data e le sue giornate: accanto al nome compare ×3 e le giornate si sommano.": "The same operation is registered several times: alfalfa is mown 3-4 times a year and irrigation is repeated all summer. Each time add a new execution with its date and its working days: next to the name ×3 appears and the days are added up.",
"CONCIMAZIONE: il form chiede quali concimi — binario, ternario, stallatico, letame o altro — e i quintali di ciascuno; se ne possono mettere più di uno nella stessa passata": "FERTILISING: the form asks which fertilisers — binary, ternary, manure, farmyard manure or other — and the quintals of each; you can enter more than one in the same pass",
"DISSERBO: il form chiede il prodotto, la quantità e se è in litri o in chilogrammi": "WEEDING: the form asks the product, the quantity and whether it is in litres or kilograms",
"La quantità per ettaro si calcola da sola sugli ettari della coltura": "The quantity per hectare is calculated by itself on the crop's hectares",
"🌾 Raccolta": "🌾 Harvest",
"Linguetta Raccolta → '+ Registra raccolta'": "Harvest tab → '+ Register harvest'",
"Scegli il PRODOTTO raccolto (non la coltura): avena, erba medica, erbaio misto, grano, orzo, paglia, pisello proteico, sulla, seme misto, seme di medica, seme di sulla, o Altro": "Choose the harvested PRODUCT (not the crop): oats, alfalfa, mixed forage, wheat, barley, straw, protein pea, sulla, mixed seed, alfalfa seed, sulla seed, or Other",
"L'unità si imposta da sola — quintali per i cereali, balloni per i foraggi — ma puoi cambiarla in quintali, balloni, rotoballe o chilogrammi": "The unit is set by itself — quintals for cereals, bales for forage — but you can change it to quintals, bales, round bales or kilograms",
"Inserisci la quantità e la data: la resa per ettaro si calcola da sola": "Enter the quantity and the date: the yield per hectare is calculated by itself",
"PAGLIA, SEME DI MEDICA e SEME DI SULLA sono sottoprodotti: escono dagli stessi ettari della coltura principale e nel riepilogo non ne raddoppiano ettari e giornate. Le colture PASCOLATE non hanno raccolta: il loro costo va tutto al pascolo.": "STRAW, ALFALFA SEED and SULLA SEED are by-products: they come from the same hectares as the main crop, and in the summary they don't double hectares and working days. GRAZED crops have no harvest: all their cost goes to grazing.",
"✏️ Correggere un dato": "✏️ Correcting a record",
"Le esecuzioni delle lavorazioni e le raccolte si correggono o si cancellano con la matita e il cestino accanto alla riga: ognuno può farlo sulle righe inserite da lui, entro 48 ore dall'inserimento. Dopo, o per le righe di altri, serve l'amministratore. Una riga corretta mostra '✏️ Corretto il…' e il valore di prima resta nello storico delle rettifiche.": "Field operation executions and harvests are corrected or deleted with the pencil and the bin next to the row: everyone can do it on the rows they entered, within 48 hours of entering them. After that, or for other people's rows, the administrator is needed. A corrected row shows '✏️ Corrected on…' and the previous value stays in the corrections history.",
"Tutti i campi della campagna raggruppati per coltura: ettari dedicati, giornate di lavoro e, per ciascun prodotto, quantità raccolta, resa per ettaro e resa per giornata di lavoro. Si compila da solo man mano che si inseriscono i dati.": "All the fields of the season grouped by crop: hectares used, working days and, for each product, quantity harvested, yield per hectare and yield per working day. It fills in by itself as the data is entered.",
"🗺️ Per campo: per ogni coltura i semi e i concimi previsti, con dose per ettaro e quantità totale (dose × ettari); le confezioni sono arrotondate per eccesso. Sotto, '▸ Istruzioni per semina e concimazione' apre le note del piano approvato": "🗺️ By field: for each crop the planned seeds and fertilisers, with dose per hectare and total quantity (dose × hectares); bags are rounded up. Below, '▸ Instructions for sowing and fertilising' opens the notes of the approved plan",
"🛒 Da acquistare: gli stessi prodotti sommati su tutta l'azienda, cioè la lista della spesa della campagna": "🛒 To buy: the same products added up for the whole farm, that is the season's shopping list",
"Il programma lo prepara l'amministratore dal piano approvato dal dott. Bizzarri; chi semina trova i semi previsti già proposti nel menu della Semina": "The plan is prepared by the administrator from the plan approved by Dr Bizzarri; whoever sows finds the planned seeds already offered in the Sowing menu",
"📈 Report — la campagna scelta": "📈 Report — the chosen season",
"Il costo di ogni coltura è semi + concimi + fitosanitari + lavorazioni + altro, dalle schede campo approvate. Le lavorazioni fatte in azienda sono valutate a tariffa, senza fattura. Il costo della coltura si divide fra tutti i suoi prodotti (paglia e seme compresi) in proporzione al valore di mercato.": "The cost of each crop is seeds + fertilisers + crop protection + field operations + other, from the approved field records. Operations done by the farm itself are valued at a standard rate, without an invoice. The crop's cost is split among all its products (straw and seed included) in proportion to market value.",
"In cima: superficie, costo totale, costo per ettaro e saldo contro il mercato": "At the top: area, total cost, cost per hectare and balance against the market",
"DOVE GUADAGNI e DOVE PERDI: i prodotti che sono costati meno o più del loro prezzo di mercato, con il semaforo (verde sotto il mercato, giallo poco sopra, rosso oltre la soglia)": "WHERE YOU GAIN and WHERE YOU LOSE: the products that cost less or more than their market price, with the traffic light (green below the market, yellow a little above, red beyond the threshold)",
"RESE CONTRO IL RIFERIMENTO: la resa per ettaro confrontata con la media ISTAT della provincia di Roma, solo per orzo, avena e favino; per fieni, paglia, sementi e pascoli un riferimento affidabile non c'è": "YIELDS AGAINST THE REFERENCE: yield per hectare compared with the ISTAT average for the province of Rome, only for barley, oats and field beans; for hay, straw, seeds and pastures there is no reliable reference",
"PASCOLI: le colture pascolate senza raccolta, con il loro costo per ettaro": "PASTURES: the grazed crops without harvest, with their cost per hectare",
"COSTI PER COLTURA: tocca una coltura per vedere i suoi campi": "COSTS BY CROP: tap a crop to see its fields",
"⚙️ Prezzi e rese: prezzi di mercato in euro al quintale, peso del ballone e della rotoballa (340 chilogrammi), soglia del semaforo e rese di riferimento. Li modifica solo l'amministratore; il report si ricalcola subito": "⚙️ Prices and yields: market prices in euro per quintal, weight of the bale and of the round bale (340 kilograms), traffic-light threshold and reference yields. Only the administrator can change them; the report recalculates at once",
"📥 Esporta Excel e 📅 Confronto tra stagioni (tutte le stagioni affiancate: superficie, costo per ettaro, saldo e produzione)": "📥 Export Excel and 📅 Comparison between seasons (all seasons side by side: area, cost per hectare, balance and production)",
"📚 Storico — tutte le stagioni": "📚 History — all seasons",
"🌱 Per coltura": "🌱 By crop",
"Stagione per stagione: ettari, resa, costo e costo di ogni unità di prodotto contro il mercato": "Season by season: hectares, yield, cost and cost of each unit of product against the market",
"🗺️ Per campo": "🗺️ By field",
"Per un campo: coltura, produzione, costi, concimi con la dose per ettaro e risultato contro il mercato": "For one field: crop, production, costs, fertilisers with the dose per hectare and result against the market",
"🏅 Ranking stagione": "🏅 Season ranking",
"In ogni stagione i campi dal migliore al peggiore per costo del prodotto rapportato al prezzo di mercato": "In each season the fields from best to worst by cost of the product compared with its market price",
"🏆 Ranking resa": "🏆 Yield ranking",
"I campi su tutte le stagioni, confrontati con gli altri della stessa coltura: 100 = media dell'azienda": "The fields over all seasons, compared with the others with the same crop: 100 = farm average",
"🥇 Ranking per coltura": "🥇 Ranking by crop",
"Per una coltura, i campi che l'hanno avuta sommando tutte le stagioni, al quintale del prodotto principale": "For one crop, the fields that had it, adding up all seasons, per quintal of the main product",
"Report e Storico non si compilano: si ricalcolano ogni volta dai dati del database. Se si corregge una scheda, un prezzo o una resa, cambiano subito. Esclusi i pascoli, che non hanno un prodotto misurato.": "Report and History are not filled in: they are recalculated every time from the database. If a record, a price or a yield is corrected, they change at once. Pastures are excluded, as they have no measured product.",
"🏭 Collegamento con la Contabilità Industriale": "🏭 Link with Cost Accounting",
"La Contabilità Industriale legge, in sola lettura, gli stessi dati delle coltivazioni attraverso le viste del database, e trova i report Excel delle coltivazioni (rese delle stagioni, schede campo, piano della campagna) nell'archivio dei report, sempre all'ultima versione. Dall'app Coltivazione non si scrive mai nei dati della Contabilità Industriale.": "Cost Accounting reads, read-only, the same crop data through the database views, and finds the crop Excel reports (season yields, field records, season plan) in the reports archive, always at the latest version. The Crops app never writes into Cost Accounting data.",
"Registro uscite": "Exits register",
"Come registrare un'uscita": "How to register an exit",
"Vai in 📤 Uscite": "Go to 📤 Exits",
"Usa i filtri specie (bovini / suini / ovini) per restringere la lista": "Use the species filters (cattle / pigs / sheep) to narrow the list",
"Cerca per BDN, ultime 4 cifre, nome, lotto o razza": "Search by BDN, last 4 digits, name, batch or breed",
"Tab 'In stalla': trova l'animale → tocca '📤 Uscita'": "'In the barn' tab: find the animal → tap '📤 Exit'",
"Scegli motivo, data, peso vivo": "Choose reason, date, live weight",
"Se macellato: inserisci peso carcassa → resa % calcolata automaticamente": "If slaughtered: enter carcass weight → yield % calculated automatically",
"I giorni di permanenza in stalla vengono calcolati automaticamente": "The days spent on the farm are calculated automatically",
"Tocca 'Registra uscita'": "Tap 'Register exit'",
"Tipi di uscita": "Types of exit",
"🔪 Macellato — con peso vivo, peso carcassa, resa %": "🔪 Slaughtered — with live weight, carcass weight, yield %",
"✝️ Morto (cause naturali o malattia)": "✝️ Dead (natural causes or disease)",
"💰 Venduto vivo": "💰 Sold alive",
"🚨 Furto · 🏃 Scappato · 🔄 Trasferito": "🚨 Theft · 🏃 Escaped · 🔄 Transferred",
"Tab 'Usciti'": "'Exited' tab",
"Storico di tutti gli animali usciti con filtro per specie. Mostra riepilogo macellazioni: peso vivo totale, carcassa totale, resa media.": "History of all exited animals with species filter. Shows a slaughter summary: total live weight, total carcass, average yield.",
"Pedigree e genealogia": "Pedigree and family tree",
"Il modulo Pedigree legge automaticamente i dati genealogici delle schede. Non serve inserire nulla in più.": "The Pedigree module reads the family data from the records automatically. Nothing extra needs to be entered.",
"Albero visuale a 3 generazioni (soggetto → genitori → nonni)": "Visual tree over 3 generations (animal → parents → grandparents)",
"Nodi cliccabili: tocca un antenato per aprirne la scheda": "Clickable nodes: tap an ancestor to open its record",
"Badge 'pedigree ✓' sugli animali con genealogia tracciata": "'pedigree ✓' badge on animals with a traced family tree",
"Storico parti con nati vivi/morti": "History of births with born alive / dead",
"Discendenti diretti con link alle schede": "Direct offspring with links to their records",
"Per un albero completo, collega sempre padre e madre nella scheda di ogni animale.": "For a complete tree, always link father and mother in every animal's record.",
"Selezione genetica": "Genetic selection",
"KPI calcolati automaticamente": "Indicators calculated automatically",
"N° parti": "Number of births",
"Totale parti registrati per femmina": "Total births registered per female",
"IIP medio": "Average calving interval",
"Intervallo inter-parto in giorni E mesi (meno = meglio)": "Interval between births in days AND months (lower = better)",
"% nati vivi": "% born alive",
"Nati vivi su totale nati": "Born alive out of total born",
"Prolificità": "Prolificacy",
"Media nati vivi per parto": "Average born alive per birth",
"Longevità": "Longevity",
"Anni di carriera riproduttiva": "Years of reproductive career",
"Massimizzare l'accuratezza del ranking": "Making the ranking as accurate as possible",
"Registra TUTTI i parti (presenti e storici) nella scheda di ogni fattrice": "Register ALL births (current and past) in the record of each breeding female",
"Per parti storici usa '📅 Parto storico' — bastano data, totali, morti": "For past births use '📅 Past birth' — date, total and dead are enough",
"Più parti hai registrati, più accurato è il ranking": "The more births are registered, the more accurate the ranking",
"Il ranking si aggiorna in tempo reale appena aggiungi nuovi eventi": "The ranking updates in real time as soon as you add new events",
"Costi — dove si guardano adesso": "Costs — where to see them now",
"L'analisi economica è passata al programma di Contabilità Industriale, che lavora sullo stesso database di questa app ed è usato dai contabili. Qui dentro restano le due cose che servono a chi sta in allevamento.": "The economic analysis has moved to the Cost Accounting program, which works on the same database as this app and is used by the accountants. Here remain the two things needed by those working with the animals.",
"💰 Costi nella scheda dell'animale": "💰 Costs in the animal's record",
"Apri un animale → tab 💰 Costi. Vedi anno per anno: UBA-giorni, categoria contabile, costo di mantenimento, costo di nascita ereditato, quota già scaricata sui figli e totale dell'anno, con il cumulato in fondo.": "Open an animal → 💰 Costs tab. You see year by year: livestock-unit days, accounting category, maintenance cost, inherited birth cost, share already passed on to the offspring and year total, with the running total at the bottom.",
"Questi numeri li CALCOLA la Contabilità Industriale, qui si leggono soltanto. Se un valore è sbagliato non si corregge da qui: si corregge là.": "These numbers are CALCULATED by Cost Accounting; here they can only be read. If a value is wrong it is not corrected here: it is corrected there.",
"⚠️ Manca costo acquisto": "⚠️ Purchase cost missing",
"Se un animale ha provenienza 'Acquistato' ma il prezzo di acquisto è vuoto, compare un badge rosso sulla sua card in Anagrafica e un avviso in cima alla scheda. Serve perché un capo comprato senza prezzo falsa tutti i conti a valle.": "If an animal has origin 'Bought' but the purchase price is empty, a red badge appears on its card in the Registry and a warning at the top of the record. It matters because an animal bought without a price distorts all the accounts downstream.",
"Per sistemarlo: apri la scheda → ✏️ Modifica → compila Prezzo acquisto → Salva": "To fix it: open the record → ✏️ Edit → fill in Purchase price → Save",
"Il campo è condiviso con la Contabilità Industriale: appena lo compili da una parte, l'avviso sparisce da entrambe": "The field is shared with Cost Accounting: as soon as you fill it in on one side, the warning disappears from both",
"Le vecchie tab Costi, Origine e Struttura": "The old Costs, Origin and Structure tabs",
"Sono state tolte dalla barra perché quel lavoro si fa ora nella Contabilità Industriale. I dati non sono stati cancellati: macchinari, ammortamenti e costi generali sono tutti ancora nel database, e le tab si possono rimettere in qualsiasi momento.": "They were removed from the bar because that work is now done in Cost Accounting. No data was deleted: machinery, depreciation and general costs are all still in the database, and the tabs can be put back at any time.",
"Storico aggiornamenti v29 → v64": "Update history v29 → v64",
"⚖️ Modifica peso carcassa su animali già usciti": "⚖️ Editing the carcass weight of animals already exited",
"Spesso passa del tempo tra il momento in cui un animale esce dall'allevamento (e un operatore registra data uscita e peso vivo) e il momento in cui arriva il referto del macello con il peso della carcassa (registrato magari da un altro operatore, giorni dopo).": "Some time often passes between the moment an animal leaves the farm (and an operator records exit date and live weight) and the moment the slaughterhouse report arrives with the carcass weight (perhaps recorded by another operator, days later).",
"Apri la scheda dell'animale già uscito dall'Anagrafica (anche se il capo non è più attivo)": "Open the record of the exited animal from the Registry (even if the animal is no longer active)",
"Tocca Modifica e vai alla sezione Dati Uscita": "Tap Edit and go to the Exit data section",
"Inserisci o correggi il Peso carcassa (kg) in qualsiasi momento, anche mesi dopo": "Enter or correct the Carcass weight (kg) at any time, even months later",
"La Resa % (carcassa/peso vivo) si ricalcola automaticamente ogni volta che aggiorni il dato": "The Yield % (carcass / live weight) is recalculated automatically every time you update the figure",
"Utile per completare progressivamente la scheda man mano che arrivano i referti dal macello": "Useful to complete the record step by step as the slaughterhouse reports arrive",
"📮 Report Mensili automatici via Email": "📮 Automatic monthly reports by Email",
"Nuovo tab 📮 Email per gestire l'invio automatico di report e backup ai soggetti registrati (commercialista, direttore allevamento, consulenti, ecc.).": "New 📮 Email tab to manage the automatic sending of reports and backups to registered people (accountant, farm manager, consultants, etc.).",
"Registra destinatari con nome, email, ruolo e permessi (Report / Backup / Alert)": "Register recipients with name, email, role and permissions (Report / Backup / Alert)",
"Il 1° di ogni mese alle 06:00 il sistema invia automaticamente via email: report Excel (anagrafica, uscite del mese, sanitario) allegato a chi ha permesso Report": "On the 1st of every month at 06:00 the system automatically sends by email: Excel report (registry, exits of the month, health) attached for those with Report permission",
"Backup completo del database (file .sql) allegato a chi ha permesso Backup": "Full database backup (.sql file) attached for those with Backup permission",
"Pulsante 🧪 Test invio per verificare il funzionamento in qualsiasi momento senza aspettare fine mese": "🧪 Test send button to check it works at any time without waiting for the end of the month",
"Storico di tutti gli invii consultabile dal tab Email": "History of all sendings in the Email tab",
"🐾 Registro Sanitario — Filtri specie e scadenze": "🐾 Health register — Species filters and due dates",
"Filtro per specie (bovino/suino/ovino/tutti) nella registrazione singola e di gruppo — utile per vaccini specie-specifici": "Species filter (cattle/pig/sheep/all) in single and group registration — useful for species-specific vaccines",
"Pulsante 🌾 Tutti per selezionare in un click tutti gli animali attivi dell'azienda": "🌾 All button to select in one click all the farm's active animals",
"11 tipi di evento sanitario (vaccino, richiamo, farmaco, antiparassitario, visita, intervento chirurgico, diagnostica, gravidanza, malattia, cura, altro)": "11 types of health event (vaccine, booster, medicine, antiparasitic, visit, surgery, diagnostics, pregnancy, disease, treatment, other)",
"Box scadenze richiami in cima al Registro Sanitario (scaduti in rosso, imminenti 30gg in giallo)": "Booster due-date box at the top of the Health register (overdue in red, due within 30 days in yellow)",
"Badge notifica sull'icona 💉 Salute nel menu con il numero di richiami da gestire": "Notification badge on the 💉 Health icon in the menu with the number of boosters to handle",
"Pulsante ✓ Registra su ogni scadenza per aprire il form già pre-compilato (nessuna registrazione automatica, sempre conferma manuale)": "✓ Register button on each due date to open the form already filled in (nothing is registered automatically, always manual confirmation)",
"📅 Timeline eventi unificata nella scheda animale": "📅 Unified event timeline in the animal record",
"Nella scheda di ogni animale, il tab 📅 Eventi mostra ora una timeline cronologica che unisce nascita, ingresso, qualifica riproduttore, parti, eventi sanitari e uscita, con separatori per anno e statistiche riassuntive in cima.": "In each animal's record, the 📅 Events tab now shows a chronological timeline joining birth, arrival, breeder qualification, births given, health events and exit, with separators by year and summary statistics at the top.",
"🐷 Lotti suini — Rifatti completamente": "🐷 Pig batches — completely redone",
"Al salvataggio del parto suino, il lotto viene creato automaticamente nella sezione Lotti": "When the pig farrowing is saved, the batch is created automatically in the Batches section",
"Nuovo pulsante 📦 Lotto acquistato — per registrare lotti comprati da terzi (fornitore, prezzo, N capi)": "New 📦 Bought batch button — to register batches bought from others (supplier, price, number of head)",
"Ogni unità del lotto ha 2 pulsanti: 🏷️ BDN (assegna matricola individuale) e 📤 Uscita (macellato/morto/venduto/predato/smarrito)": "Each unit of the batch has 2 buttons: 🏷️ BDN (assign individual ID number) and 📤 Exit (slaughtered/dead/sold/killed by predators/lost)",
"Quando assegni un BDN a un suinetto del lotto, esce dal lotto ed entra nel Registro Suini con tutti i dati ereditati": "When you assign a BDN to a piglet of the batch, it leaves the batch and enters the Pig register with all inherited data",
"Quando tutti i suinetti hanno BDN o sono usciti, il lotto si chiude automaticamente": "When all piglets have a BDN or have exited, the batch closes automatically",
"🧬 Genitori esterni nel form animale e parto": "🧬 External parents in the animal and birth forms",
"Nel form animale e nel form parto, accanto al menu genitori aziendali, ora c'è un campo per inserire la matricola di un padre esterno (non registrato in azienda). Al salvataggio l'app crea automaticamente una scheda minima per quel padre esterno, con la razza scelta. Comparirà nel Pedigree e sarà disponibile per parti futuri.": "In the animal form and in the birth form, next to the farm parents menu, there is now a field to enter the ID number of an external father (not registered on the farm). When saving, the app automatically creates a minimal record for that external father, with the chosen breed. It will appear in the Pedigree and be available for future births.",
"🐾 Sezione UBA — Nuova": "🐾 Livestock units section — New",
"Calcolo delle Unità di Bestiame Adulto (UBA) per ogni animale con media ponderata secondo la fascia di età. Base per la ripartizione dei costi. Dati chiave:": "Calculation of Livestock Units (LU) for each animal with a weighted average by age band. Basis for splitting costs. Key data:",
"UBA medio = coefficiente medio ponderato tra le fasce di età nel periodo di calcolo": "Average LU = weighted average coefficient over the age bands in the calculation period",
"Periodo di calcolo = MAX(nascita, 1° gennaio) → oggi (o data uscita)": "Calculation period = MAX(birth, 1 January) → today (or exit date)",
"UBA-giorni = UBA medio × giorni nel periodo (base per la ripartizione costi)": "LU-days = average LU × days in the period (basis for splitting costs)",
"Data di riferimento configurabile (utile per bilanci parziali)": "Configurable reference date (useful for interim accounts)",
"Filtri per specie (tutti / bovino / suino / ovino) e per stato (attivi / usciti / tutti)": "Filters by species (all / cattle / pig / sheep) and by status (active / exited / all)",
"🧬 Consanguineità — Nuova sezione nel Pedigree": "🧬 Inbreeding — New section in Pedigree",
"Nella scheda animale del Pedigree c'è ora il tab 🚫 Consanguineità con elenco genitori/figli/fratelli": "In the Pedigree animal record there is now the 🚫 Inbreeding tab with the list of parents/offspring/siblings",
"Report Excel con due fogli: Accoppiamenti a rischio (prevenzione monta) e Capi con genealogia consanguinea": "Excel report with two sheets: Risky matings (mating prevention) and Animals with inbred ancestry",
"Nell'elenco a schermo degli accoppiamenti a rischio, accanto a nome e matricola di maschio e femmina compare la RAZZA in evidenza — utile per capire subito se la coppia riguarda animali di razza pregiata": "In the on-screen list of risky matings, next to the name and ID number of male and female, the BREED is highlighted — useful to see at once whether the pair concerns valuable breeds",
"🏷️ Data registrazione BDN — Nuovo campo": "🏷️ BDN registration date — New field",
"Ora ogni animale ha due date: data di nascita e data registrazione BDN (attribuzione ufficiale matricola). Compare nella scheda e nell'export.": "Every animal now has two dates: date of birth and BDN registration date (official assignment of the ID number). It appears in the record and in the export.",
"♀ Riproduttrice — Qualifica automatica": "♀ Breeding female — Automatic qualification",
"Il toggle riproduttore/riproduttrice è ora disponibile anche per le femmine": "The breeder switch is now available for females too",
"Alla registrazione di un parto, la madre viene marcata automaticamente come riproduttrice": "When a birth is registered, the mother is automatically marked as a breeding female",
"Il Registro Riproduttori mostra sia maschi (♂) sia femmine (♀)": "The Breeders register shows both males (♂) and females (♀)",
"🏆 Selezione Genetica — Nuovi indicatori": "🏆 Genetic Selection — New indicators",
"Età al primo parto (mesi)": "Age at first birth (months)",
"Produttività annua stimata (figli/anno di carriera)": "Estimated yearly productivity (offspring per year of career)",
"🥩 Statistiche figli macellati: resa carcassa media, peso carcassa medio, IPG carcassa medio dei figli — indicatore genetico del valore del riproduttore per la resa": "🥩 Statistics of slaughtered offspring: average carcass yield, average carcass weight, average carcass daily gain of the offspring — genetic indicator of the breeder's value for yield",
"📈 IPG — Incremento Peso Giornaliero": "📈 Daily weight gain",
"Calcolato automaticamente dove ci sono peso ingresso e peso uscita:": "Calculated automatically where arrival weight and exit weight are present:",
"IPG peso vivo (kg/gg) = peso_vivo_uscita / giorni_permanenza": "Live weight daily gain (kg/day) = exit live weight / days on the farm",
"IPG carcassa (kg/gg) = peso_carcassa / giorni_permanenza": "Carcass daily gain (kg/day) = carcass weight / days on the farm",
"Compare nella scheda animale uscito, nel Registro Uscite, e negli export Excel": "It appears in the exited animal's record, in the Exits register, and in the Excel exports",
"📤 Filtro Attivi / Usciti in tutte le sezioni": "📤 Active / Exited filter in all sections",
"Anagrafica, Pedigree e Selezione Genetica hanno un doppio filtro: specie + stato (Attivi / Usciti / Tutti). Default: solo Attivi. Nell'Export gli animali attivi e usciti sono in fogli separati.": "Registry, Pedigree and Genetic Selection have a double filter: species + status (Active / Exited / All). Default: Active only. In the Export, active and exited animals are in separate sheets.",
"🐄 Nuova razza bovina: Limousine": "🐄 New cattle breed: Limousine",
"Aggiunta alle razze bovine disponibili sia nel form animale sia nel form padre esterno.": "Added to the cattle breeds available both in the animal form and in the external father form.",
"👥 Parti gemellari bovini e ovini": "👥 Twin births in cattle and sheep",
"Registrando un parto con più nati vivi, l'app apre un blocco per ogni gemello con matricola, sesso e peso individuali.": "When a birth with several live newborns is registered, the app opens a block for each twin with individual ID number, sex and weight.",
"Novità v65 → v119 (settembre 2026)": "New in v65 → v119 (September 2026)",
"🌾 Coltivazione: costi, report, storico e programma (v115 → v119)": "🌾 Crops: costs, report, history and plan (v115 → v119)",
"Caricate le schede campo approvate dal 2019/2020 al 2025/2026 con i costi. Nuove linguette 📈 Report (costi, mercato, rese di riferimento ISTAT, semaforo, esportazione Excel, confronto tra stagioni), 📚 Storico (per coltura, per campo e tre classifiche) e 🗓️ Programma (semina e concimazione per campo, lista degli acquisti). Nella Semina il seme si sceglie da un elenco, con i semi del programma in cima. Balloni e rotoballe a 340 chilogrammi. Tutto descritto nella sezione Coltivazione di questa guida.": "The approved field records from 2019/2020 to 2025/2026 have been loaded with their costs. New tabs 📈 Report (costs, market, ISTAT reference yields, traffic light, Excel export, comparison between seasons), 📚 History (by crop, by field and three rankings) and 🗓️ Plan (sowing and fertilising by field, shopping list). In Sowing the seed is chosen from a list, with the plan's seeds at the top. Bales and round bales at 340 kilograms. All described in the Crops section of this guide.",
"🌾 Sezione Coltivazione — completamente nuova": "🌾 Crops section — completely new",
"I 16 campi aziendali con foto aeree, catasto, colture per campagna, semine, le 15 lavorazioni ripetibili, raccolta per prodotto e riepilogo rese. Ha una sua sezione dedicata in questa guida.": "The 16 farm fields with aerial photos, land registry, crops by season, sowing, the 15 repeatable field operations, harvest by product and yield summary. It has its own section in this guide.",
"⚖️ Storico Pesate": "⚖️ Weighing history",
"Nuovo tab nella scheda animale: ogni pesata è una riga, con tipo di rilevazione e distinzione fra peso reale e stimato. Sostituisce il vecchio campo unico che si sovrascriveva. Vedi la sezione Pesate.": "New tab in the animal record: every weighing is a row, with type of measurement and distinction between real and estimated weight. It replaces the old single field that was overwritten. See the Weighings section.",
"♂ I maschi non nascono più riproduttori": "♂ Males are no longer breeders from birth",
"Correzione importante: prima ogni maschio veniva marcato riproduttore automaticamente alla nascita. Ora lo diventa solo con l'attivazione esplicita del toggle, e viene registrata la data di qualifica. Le femmine restano automatiche al primo parto.": "Important correction: before, every male was automatically marked as a breeder at birth. Now it becomes one only when the switch is turned on explicitly, and the qualification date is recorded. Females are still automatic at their first birth.",
"💰 Costi nella scheda animale": "💰 Costs in the animal record",
"Nuovo tab 💰 Costi: mostra anno per anno i costi calcolati dalla Contabilità Industriale, con UBA-giorni, mantenimento, quota scaricata sui figli e cumulato. Sola lettura.": "New 💰 Costs tab: shows year by year the costs calculated by Cost Accounting, with livestock-unit days, maintenance, share passed on to offspring and running total. Read only.",
"⚠️ Avviso costo di acquisto mancante": "⚠️ Missing purchase cost warning",
"Badge rosso in Anagrafica e avviso nella scheda quando un animale acquistato non ha il prezzo. Lo stesso avviso compare nella Contabilità Industriale, ed è lo stesso campo: si compila da una parte e sparisce da entrambe.": "Red badge in the Registry and warning in the record when a bought animal has no price. The same warning appears in Cost Accounting, and it is the same field: fill it in on one side and it disappears from both.",
"📏 Peso all'ingresso": "📏 Arrival weight",
"Nuovo campo accanto a peso nascita e peso attuale, per registrare quanto pesava l'animale quando è entrato in azienda. Serve soprattutto per gli acquistati, di cui il peso di nascita vero non si conosce.": "New field next to birth weight and current weight, to record how much the animal weighed when it arrived on the farm. Useful above all for bought animals, whose real birth weight is unknown.",
"🐷 I costi seguono il suinetto quando prende il BDN": "🐷 Costs follow the piglet when it gets its BDN",
"Quando assegni un BDN a un'unità di lotto, i costi che quella unità aveva già maturato mentre stava nel lotto vengono ricollegati alla nuova scheda animale, invece di ripartire da zero.": "When you assign a BDN to a batch unit, the costs that unit had already built up while in the batch are linked to the new animal record, instead of starting again from zero.",
"📅 Giorni di vita nell'export": "📅 Days of life in the export",
"Nuova colonna nell'export Excel degli animali, subito dopo Data uscita: i giorni fra nascita e uscita, che prima andavano calcolati a mano ogni volta.": "New column in the animals Excel export, right after Exit date: the days between birth and exit, which before had to be calculated by hand every time.",
"🗺️ Barra dei moduli riordinata": "🗺️ Module bar reordered",
"Tolte dalla barra 📊 Costi, 🧾 Origine e 🏭 Struttura, il cui lavoro è passato alla Contabilità Industriale. Aggiunta 🌾 Coltivazione. Nessun dato è stato cancellato.": "Removed from the bar 📊 Costs, 🧾 Origin and 🏭 Structure, whose work has moved to Cost Accounting. Added 🌾 Crops. No data was deleted.",
"🚫 Accoppiamenti a rischio ordinati per priorità genetica": "🚫 Risky matings ordered by genetic priority",
"Nel Report Consanguineità, dentro ogni specie, le coppie a rischio sono ora raggruppate per gravità genetica. Il meticcio non è una razza ma il risultato di un incrocio, quindi la consanguineità fra due soggetti della stessa razza pura pesa molto più che fra due meticci.": "In the Inbreeding Report, within each species, risky pairs are now grouped by genetic seriousness. A crossbred is not a breed but the result of a cross, so inbreeding between two animals of the same pure breed weighs much more than between two crossbreds.",
"1. Stessa razza": "1. Same breed",
"I due animali sono della stessa razza pura — il caso più grave, si concentra la parentela dentro una linea di sangue di valore": "The two animals are of the same pure breed — the most serious case, kinship is concentrated within a valuable bloodline",
"2. Razze pure diverse": "2. Different pure breeds",
"Due razze pure differenti — comunque due soggetti di pregio": "Two different pure breeds — still two valuable animals",
"3. Razza × meticcio": "3. Breed × crossbred",
"Un animale di razza pura con un meticcio": "A purebred animal with a crossbred",
"4. Meticcio × meticcio": "4. Crossbred × crossbred",
"Entrambi incroci — rilevanza genetica minore": "Both crosses — less genetic relevance",
"5. Razza non indicata": "5. Breed not given",
"Manca la razza su almeno uno dei due: va completata nella scheda": "The breed is missing on at least one of the two: it must be completed in the record",
"Lo stesso ordine si ritrova nel file Excel, sia in quello del pulsante 📊 Excel dentro il Report Consanguineità sia nel foglio 'Accoppiamenti a rischio' del modulo 📥 Esporta: le righe sono ordinate per specie e priorità, con due colonne in più (Priorità e Categoria) per poter filtrare.": "The same order is found in the Excel file, both from the 📊 Excel button inside the Inbreeding Report and in the 'Risky matings' sheet of the 📥 Export module: rows are ordered by species and priority, with two extra columns (Priority and Category) for filtering.",
"🔢 Numero di versione nel menu": "🔢 Version number in the menu",
"Toccando il proprio nome in alto a destra, sotto il ruolo compare ora la versione dell'app. Serve a capire in un attimo se un aggiornamento è arrivato davvero o se il browser sta mostrando una copia vecchia: in quel caso basta ricaricare con Ctrl+F5.": "Tapping your name at the top right, the app version now appears under the role. It helps to see at once whether an update has really arrived or the browser is showing an old copy: in that case just reload with Ctrl+F5.",
"Esportare dati in Excel": "Exporting data to Excel",
"Il tab 📥 Esporta permette di generare un file Excel su misura con solo i dati che ti servono.": "The 📥 Export tab lets you create a tailored Excel file with only the data you need.",
"Come funziona": "How it works",
"Vai in 📥 Esporta": "Go to 📥 Export",
"Imposta opzionalmente un filtro data (Da / A) — si applica a sanitario, alimentazione, parti, costi": "Optionally set a date filter (From / To) — it applies to health, feeding, births, costs",
"Spunta le sezioni da includere (o usa 'Seleziona tutto')": "Tick the sections to include (or use 'Select all')",
"Tocca '📥 Genera Excel (N fogli)' — il file viene scaricato automaticamente": "Tap '📥 Create Excel (N sheets)' — the file downloads automatically",
"Sezioni esportabili": "Sections that can be exported",
"🐄 Anagrafica Bovini": "🐄 Cattle registry",
"Tutti i dati di ogni bovino: BDN, razza, pesi, provenienza, uscita, resa": "All data of each bovine: BDN, breed, weights, origin, exit, yield",
"🐷 Anagrafica Suini": "🐷 Pig registry",
"Come sopra per i suini con matricola": "As above for pigs with ID number",
"🐑 Anagrafica Ovini": "🐑 Sheep registry",
"Come sopra per gli ovini": "As above for sheep",
"Tutti gli animali usciti con giorni permanenza e resa macellazione": "All exited animals with days on the farm and slaughter yield",
"🐣 Parti": "🐣 Births",
"Registro completo parti per specie con padre, madre, nati": "Complete register of births by species with father, mother, newborns",
"💉 Sanitario": "💉 Health",
"Tutti gli eventi sanitari inclusi i trattamenti su lotti suini": "All health events including treatments on pig batches",
"🌾 Alimentazione": "🌾 Feeding",
"Tutte le somministrazioni": "All feedings",
"📋 Lotti Riepilogo": "📋 Batches summary",
"Un lotto per riga: vivi/macellati/deceduti/riproduttori/maschi/femmine": "One batch per row: alive/slaughtered/dead/breeders/males/females",
"🏷️ Lotti Unità": "🏷️ Batch units",
"Una riga per ogni suinetto con tatuaggio, stato, pesi, resa": "One row for each piglet with tattoo, status, weights, yield",
"🏆 KPI Selezione": "🏆 Selection indicators",
"IIP giorni e mesi, prolificità, % vivi per ogni fattrice": "Calving interval in days and months, prolificacy, % alive for each breeding female",
"🧾 Costi Animale": "🧾 Animal costs",
"Costi per singolo animale": "Costs per single animal",
"📊 Costi Generali": "📊 General costs",
"Costi fissi aziendali": "Fixed farm costs",
"🐄 Bovini attivi/usciti": "🐄 Active/exited cattle",
"Fogli separati per attivi e usciti": "Separate sheets for active and exited",
"🐷 Suini attivi/usciti": "🐷 Active/exited pigs",
"Come sopra": "As above",
"🐑 Ovini attivi/usciti": "🐑 Active/exited sheep",
"🐾 UBA Riepilogo": "🐾 Livestock units summary",
"Aggregato UBA totali e UBA-giorni per specie e categoria": "Total livestock units and LU-days by species and category",
"📋 UBA Dettaglio (tutti/bovini/ovini/suini)": "📋 Livestock units detail (all/cattle/sheep/pigs)",
"Dettaglio animali con UBA medio, UBA-giorni, categoria, stato": "Animal detail with average LU, LU-days, category, status",
"⚠️ Accoppiamenti a rischio": "⚠️ Risky matings",
"Coppie maschio-femmina attive che sono consanguinee": "Active male-female pairs that are related",
"🧬 Capi con genealogia consanguinea": "🧬 Animals with inbred ancestry",
"Animali attivi nati da unioni consanguinee": "Active animals born from related parents",
"🏭 Macchinari": "🏭 Machinery",
"Con quota annua, totale ammortizzato e valore residuo calcolati": "With yearly share, total depreciated and residual value calculated",
"Il file Excel scaricato contiene un foglio separato per ogni sezione selezionata. Il nome del file include la data di export.": "The downloaded Excel file has a separate sheet for each selected section. The file name includes the export date.",
"Guida per Allevatori": "Guide for Farm Workers",
"App Allevamento": "Farm App",
"Tutti i dati vengono salvati automaticamente nel database condiviso. Ogni operatore vede gli stessi dati in tempo reale da qualsiasi dispositivo.": "All data is saved automatically in the shared database. Every operator sees the same data in real time from any device.",
"Caricamento...": "Loading...",
"Allevamento": "Farm",
"Ruolo": "Role",
"Versione": "Version",
"Lingua": "Language",
"Esporta tutto in Excel": "Export everything to Excel",
"Guida per allevatori": "Guide for farm workers",
"Esci": "Sign out",
"Gestione": "Management",
"Pedigree": "Pedigree",
"Lotti": "Batches",
"Coltivazione": "Crops",
"Gasolio": "Diesel",
"Selezione": "Selection",
"Uscite": "Exits",
"UBA": "LU",
"Esporta": "Export",
"Email": "Email",
"Guida": "Guide",
"Inserisci email e password": "Enter email and password",
"Credenziali non valide. Riprova.": "Wrong email or password. Try again.",
"Compila tutti i campi": "Fill in all the fields",
"Password minimo 6 caratteri": "Password must be at least 6 characters",
"Registrazione completata! Controlla la tua email per confermare l'account.": "Registration complete! Check your email to confirm the account.",
"Gestione zootecnica integrata": "Integrated livestock management",
"Accedi": "Sign in",
"Registrati": "Sign up",
"Nome e cognome": "Name and surname",
"Password": "Password",
"Crea account": "Create account",
"Non hai un account?": "No account yet?"
};
export default D;
