// Traduzioni hindi dell'app: chiave = testo italiano (vedi src/i18n.js)
// File generato: si aggiorna insieme ai testi dell'app.
const D = {
"Accesso e installazione": "लॉगिन और इंस्टॉल",
"Primo accesso": "पहली बार लॉगिन",
"Apri Chrome o Safari sul telefono o PC": "फ़ोन या कंप्यूटर पर Chrome या Safari खोलें",
"Vai su www.podereverdeapp.it": "www.podereverdeapp.it पर जाएँ",
"Tocca 'Registrati' → inserisci nome, email, password → 'Crea account'": "'रजिस्टर करें' दबाएँ → नाम, ईमेल, पासवर्ड डालें → 'खाता बनाएँ'",
"Accedi subito — nessuna conferma email necessaria": "तुरंत लॉगिन करें — ईमेल की पुष्टि की ज़रूरत नहीं",
"Installa sul telefono (accesso rapido senza browser)": "फ़ोन पर इंस्टॉल करें (ब्राउज़र के बिना जल्दी खोलने के लिए)",
"Android — Chrome: menu ⋮ → 'Aggiungi a schermata Home'": "Android — Chrome: मेनू ⋮ → 'होम स्क्रीन में जोड़ें'",
"iPhone — Safari: icona 📤 → 'Aggiungi a schermata Home'": "iPhone — Safari: 📤 आइकन → 'होम स्क्रीन में जोड़ें'",
"Tutti i dati vengono salvati automaticamente nel database condiviso. Ogni operatore vede gli stessi dati in tempo reale da qualsiasi dispositivo. ⚠️ Usa sempre il browser in modalità normale (non in incognito) per restare connesso.": "सारा डेटा साझा डेटाबेस में अपने आप सेव होता है। हर कर्मचारी किसी भी डिवाइस से एक ही डेटा तुरंत देखता है। ⚠️ लॉगिन बने रहने के लिए ब्राउज़र हमेशा सामान्य मोड में चलाएँ (इनकॉग्निटो में नहीं)।",
"Navigazione — tutti i moduli": "नेविगेशन — सभी मॉड्यूल",
"In basso ci sono i pulsanti per le sezioni principali. Scorri la barra per vederli tutti.": "नीचे मुख्य हिस्सों के बटन हैं। सब देखने के लिए पट्टी को खिसकाएँ।",
"🐄 Gestione": "🐄 प्रबंधन",
"Anagrafica animali, sanitario, alimentazione, magazzino, report, riproduttori": "पशु रजिस्टर, स्वास्थ्य, आहार, भंडार, रिपोर्ट, प्रजनक पशु",
"🧬 Pedigree": "🧬 वंशावली",
"Albero genealogico, consanguineità, prevenzione accoppiamenti a rischio": "वंश वृक्ष, निकट-संबंधी प्रजनन, जोखिम वाले मिलन की रोकथाम",
"🐷 Lotti": "🐷 लॉट",
"Lotti suini (nati e acquistati) con tatuaggio automatico": "सूअरों के लॉट (फ़ार्म पर जन्मे और खरीदे गए) अपने आप बनने वाले टैटू के साथ",
"🌾 Coltivazione": "🌾 खेती",
"I campi aziendali: colture, semine, lavorazioni, raccolta, programma, costi, report e storico": "फ़ार्म के खेत: फ़सलें, बुवाई, खेत के काम, कटाई, योजना, लागत, रिपोर्ट और इतिहास",
"🏆 Selezione": "🏆 चयन",
"Ranking genetico: IIP, produttività, età primo parto, resa media figli": "आनुवंशिक रैंकिंग: ब्यांत अंतराल, उत्पादकता, पहले ब्यांत की उम्र, संतानों की औसत उपज",
"📤 Uscite": "📤 निकासी",
"Macellazioni, vendite, morti — con resa % e IPG": "वध, बिक्री, मृत्यु — उपज % और रोज़ाना वज़न बढ़त के साथ",
"🐾 UBA": "🐾 पशु इकाई",
"Calcolo UBA medio per fascia di età con ripartizione presenza effettiva": "उम्र के वर्ग के अनुसार औसत पशु इकाई, असली मौजूदगी के हिसाब से",
"📥 Esporta": "📥 निर्यात",
"Export Excel granulare — anagrafica, uscite, UBA, consanguineità": "विस्तृत Excel निर्यात — रजिस्टर, निकासी, पशु इकाई, निकट-संबंधी प्रजनन",
"📮 Email": "📮 ईमेल",
"Destinatari e invio automatico mensile di report e backup": "प्राप्तकर्ता और रिपोर्ट व बैकअप का हर महीने अपने आप भेजा जाना",
"📖 Guida": "📖 मार्गदर्शिका",
"Questo manuale": "यह पुस्तिका",
"Le vecchie tab 📊 Costi, 🧾 Origine e 🏭 Struttura non sono più nella barra: i costi per animale si consultano ora direttamente nella scheda dell'animale (tab 💰 Costi), e il grosso dell'analisi economica è passato al programma di Contabilità Industriale. I dati non sono stati cancellati.": "पुराने टैब 📊 लागत, 🧾 उत्पत्ति और 🏭 ढाँचा अब पट्टी में नहीं हैं: हर पशु की लागत अब सीधे पशु के रिकॉर्ड में दिखती है (💰 लागत टैब), और ज़्यादातर आर्थिक विश्लेषण अब लागत लेखा (Contabilità Industriale) प्रोग्राम में होता है। कोई डेटा मिटाया नहीं गया।",
"Scheda animale — cercare, consultare, modificare": "पशु रिकॉर्ड — खोजना, देखना, बदलना",
"Trovare un animale": "पशु को खोजना",
"Vai in 🐄 Gestione → tab 🏷️ Animali": "🐄 प्रबंधन → 🏷️ पशु टैब पर जाएँ",
"Usa la barra di ricerca: digita BDN completo, ultime 4 cifre del codice, nome o razza": "खोज पट्टी में लिखें: पूरा BDN कोड, कोड के आख़िरी 4 अंक, नाम या नस्ल",
"Usa i filtri specie (bovino / suino / ovino) e 'Solo attivi'": "प्रजाति के फ़िल्टर (गाय-बैल / सूअर / भेड़) और 'केवल सक्रिय' का उपयोग करें",
"Aprire la scheda": "रिकॉर्ड खोलना",
"Tocca il pulsante colorato '📋 Apri scheda completa' su ogni card. La scheda ha 5 tab:": "हर कार्ड पर रंगीन बटन '📋 पूरा रिकॉर्ड खोलें' दबाएँ। रिकॉर्ड में 5 टैब हैं:",
"📋 Info": "📋 जानकारी",
"BDN, razza, sesso, nascita, pesi, provenienza, azienda origine, prezzo acquisto, costo nascita, stato, vaccinazioni ricevute": "BDN, नस्ल, लिंग, जन्म, वज़न, उत्पत्ति, मूल फ़ार्म, खरीद मूल्य, जन्म लागत, स्थिति, लगे हुए टीके",
"🧬 Genealogia": "🧬 वंश",
"Padre, madre, discendenti diretti — cliccabili": "पिता, माता, सीधी संतानें — सब पर क्लिक किया जा सकता है",
"📅 Eventi": "📅 घटनाएँ",
"Timeline di tutto: nascita, ingresso, parti, eventi sanitari, uscita": "सब कुछ समय के क्रम में: जन्म, आगमन, ब्यांत, स्वास्थ्य घटनाएँ, निकासी",
"💰 Costi": "💰 लागत",
"Costi anno per anno calcolati dalla Contabilità Industriale — sola lettura": "लागत लेखा द्वारा गणना की गई साल-दर-साल लागत — केवल पढ़ने के लिए",
"⚖️ Pesate": "⚖️ वज़न",
"Storico di tutte le pesate dell'animale nel tempo": "पशु के सभी वज़न का समय के साथ इतिहास",
"Modificare i dati": "डेटा बदलना",
"Dalla scheda tocca ✏️ in alto a destra → modifica quello che vuoi → Salva.": "रिकॉर्ड में ऊपर दाईं ओर ✏️ दबाएँ → जो बदलना है बदलें → सहेजें।",
"Registrare un nuovo animale": "नया पशु दर्ज करना",
"Tocca '+ Aggiungi' in cima alla lista": "सूची के ऊपर '+ जोड़ें' दबाएँ",
"Seleziona SPECIE — i campi cambiano per bovino / suino / ovino": "प्रजाति चुनें — गाय-बैल / सूअर / भेड़ के लिए फ़ील्ड बदल जाते हैं",
"Inserisci BDN / Matricola, nome (facoltativo), razza, categoria, sesso, data nascita": "BDN / पहचान संख्या, नाम (वैकल्पिक), नस्ल, श्रेणी, लिंग, जन्म तिथि डालें",
"Per acquistati: provenienza 'Acquistato' → compilare prezzo acquisto e azienda di origine": "खरीदे गए पशु के लिए: उत्पत्ति 'खरीदा गया' → खरीद मूल्य और मूल फ़ार्म भरें",
"Per maschi destinati alla riproduzione: attiva il toggle '♂ Riproduttore'": "प्रजनन के लिए रखे नर के लिए: '♂ प्रजनक' चालू करें",
"Collega padre e madre dalla lista per la genealogia": "वंश के लिए सूची से पिता और माता जोड़ें",
"La razza del figlio viene calcolata: stessa razza → pura; razze diverse → METICCIA": "संतान की नस्ल अपने आप तय होती है: एक ही नस्ल → शुद्ध; अलग नस्लें → संकर",
"Tocca Salva": "सहेजें दबाएँ",
"Registro riproduttori": "प्रजनक पशुओं का रजिस्टर",
"Registrare un maschio come riproduttore": "नर को प्रजनक के रूप में दर्ज करना",
"Cerca il maschio nella lista Animali": "पशु सूची में नर को खोजें",
"Apri la scheda → ✏️ Modifica": "रिकॉर्ड खोलें → ✏️ बदलें",
"Attiva il toggle '♂ Riproduttore' (compare solo per i maschi)": "'♂ प्रजनक' चालू करें (यह केवल नर के लिए दिखता है)",
"Salva": "सहेजें",
"Consultare il registro riproduttori": "प्रजनक रजिस्टर देखना",
"In cima alla lista Animali tocca '♂ Riproduttori'. Vedi tutti i maschi registrati divisi per specie con nome, razza, età e numero di figli già registrati. Tocca una card per aprire la scheda.": "पशु सूची के ऊपर '♂ प्रजनक' दबाएँ। सभी दर्ज नर प्रजाति के अनुसार दिखते हैं — नाम, नस्ल, उम्र और दर्ज संतानों की संख्या के साथ। रिकॉर्ड खोलने के लिए कार्ड दबाएँ।",
"Nel form parto, il campo 'Padre' mostra SOLO i maschi registrati come riproduttori della stessa specie. Se non ne hai ancora, mostra tutti i maschi come alternativa.": "ब्यांत के फ़ॉर्म में 'पिता' फ़ील्ड केवल उसी प्रजाति के दर्ज प्रजनक नर दिखाता है। अगर अभी कोई नहीं है, तो सभी नर दिखाता है।",
"⚠️ Cambiato: i maschi NON nascono più riproduttori": "⚠️ बदलाव: नर अब जन्म से प्रजनक नहीं होते",
"Fino all'estate 2026 ogni maschio veniva marcato riproduttore automaticamente alla nascita, solo perché maschio. Era sbagliato e gonfiava il registro. Da settembre 2026 un maschio nasce NON riproduttore: lo diventa solo quando qualcuno attiva a mano il toggle '♂ Riproduttore' nella sua scheda.": "2026 की गर्मियों तक हर नर जन्म पर अपने आप प्रजनक मान लिया जाता था, सिर्फ़ इसलिए कि वह नर था। यह गलत था और रजिस्टर बढ़ा देता था। सितंबर 2026 से नर प्रजनक के बिना जन्म लेता है: वह तभी प्रजनक बनता है जब कोई उसके रिकॉर्ड में हाथ से '♂ प्रजनक' चालू करे।",
"Le femmine restano invece automatiche: diventano riproduttrici al primo parto registrato": "मादाएँ अब भी अपने आप बनती हैं: पहला ब्यांत दर्ज होते ही वे प्रजनक बन जाती हैं",
"Dalla data in cui attivi il toggle, l'app registra anche la data di qualifica, che compare nella timeline del tab 📅 Eventi": "जिस दिन आप इसे चालू करते हैं, ऐप योग्यता की तारीख भी दर्ज करता है, जो 📅 घटनाएँ टैब में दिखती है",
"Se un vecchio maschio risulta riproduttore per sbaglio, apri la scheda, Modifica, e spegni il toggle": "अगर कोई पुराना नर गलती से प्रजनक दिख रहा है, तो रिकॉर्ड खोलें, बदलें, और इसे बंद करें",
"Registrare un parto (bovini e ovini)": "ब्यांत दर्ज करना (गाय-बैल और भेड़)",
"Nuovo parto (crea schede figli)": "नया ब्यांत (संतानों के रिकॉर्ड बनाता है)",
"Apri la scheda della MADRE": "माँ का रिकॉर्ड खोलें",
"Tab '📅 Eventi' → '🐣 Nuovo parto'": "'📅 घटनाएँ' टैब → '🐣 नया ब्यांत'",
"Inserisci data, tipo parto, N° nati TOTALI e N° nati morti": "तारीख, ब्यांत का प्रकार, कुल जन्मे और मरे हुए जन्मे की संख्या डालें",
"I nati vivi sono calcolati automaticamente (totali − morti)": "ज़िंदा जन्मे अपने आप गिने जाते हैं (कुल − मरे हुए)",
"Seleziona il padre dalla lista riproduttori": "प्रजनक सूची से पिता चुनें",
"Per ogni nato vivo: BDN, sesso, peso nascita": "हर ज़िंदा बच्चे के लिए: BDN, लिंग, जन्म का वज़न",
"Tocca 'Registra parto'": "'ब्यांत दर्ज करें' दबाएँ",
"Le schede dei nati vengono create AUTOMATICAMENTE con razza calcolata, madre, padre, data nascita e provenienza 'Nato in azienda'.": "बच्चों के रिकॉर्ड अपने आप बनते हैं — नस्ल, माँ, पिता, जन्म तिथि और उत्पत्ति 'फ़ार्म पर जन्मा' के साथ।",
"Parto storico (solo statistiche)": "पुराना ब्यांत (केवल आँकड़ों के लिए)",
"Tocca '📅 Parto storico'": "'📅 पुराना ब्यांत' दबाएँ",
"Inserisci: data, nati totali, nati morti": "डालें: तारीख, कुल जन्मे, मरे हुए जन्मे",
"Nessun BDN richiesto — utile per parti già avvenuti con figli non in azienda": "BDN की ज़रूरत नहीं — उन पुराने ब्यांतों के लिए उपयोगी जिनके बच्चे फ़ार्म पर नहीं हैं",
"Alimenta automaticamente la Selezione Genetica per il calcolo IIP": "यह ब्यांत अंतराल के लिए आनुवंशिक चयन को अपने आप जानकारी देता है",
"Modificare o eliminare un parto": "ब्यांत बदलना या मिटाना",
"Nel tab 📅 Eventi: ogni parto mostra ✏️ (modifica dati) e 🗑️ (elimina evento). La modifica aggiorna solo i dati statistici — le schede dei figli già creati non vengono toccate.": "📅 घटनाएँ टैब में हर ब्यांत के साथ ✏️ (डेटा बदलें) और 🗑️ (घटना मिटाएँ) दिखता है। बदलने से केवल आँकड़े बदलते हैं — पहले से बने बच्चों के रिकॉर्ड नहीं छुए जाते।",
"Gestione parto e lotti suini": "सूअरों का ब्यांत और लॉट",
"Identificazione suini — due sistemi normativi": "सूअरों की पहचान — दो क़ानूनी तरीके",
"Matricola individuale": "व्यक्तिगत पहचान संख्या",
"Razze pregiate (Cinta Senese, Nero Apucalabro, Mora Romagnola, Nero Casertano) e riproduttori (verri e scrofe)": "कीमती नस्लें (Cinta Senese, Nero Apucalabro, Mora Romagnola, Nero Casertano) और प्रजनक (नर सूअर और मादा सूअर)",
"Codice lotto (tatuaggio)": "लॉट कोड (टैटू)",
"Animali da ingrasso — tutti i suinetti di un parto portano lo stesso numero tatuato sull'orecchio": "मोटा करने वाले पशु — एक ब्यांत के सभी बच्चों के कान पर एक ही नंबर का टैटू होता है",
"Codice lotto — come viene generato": "लॉट कोड — कैसे बनता है",
"Il codice è composto da: AA (anno) + MM (mese) + lettera razza madre + lettera razza padre + ultime 2 cifre matricola madre.": "कोड बनता है: YY (साल) + MM (महीना) + माँ की नस्ल का अक्षर + पिता की नस्ल का अक्षर + माँ की पहचान संख्या के आख़िरी 2 अंक।",
"Nero Apucalabro": "Nero Apucalabro",
"Cinta Senese": "Cinta Senese",
"Duroc": "Duroc",
"Mora Romagnola": "Mora Romagnola",
"Large White": "Large White",
"Meticcio": "संकर",
"Nero Casertano": "Nero Casertano",
"Landrace": "Landrace",
"Altra": "अन्य",
"Esempio: madre Cinta Senese matricola 392019 + padre Cinta Senese + parto 22/04/2023 → codice lotto 2304CC19. Unità: 2304CC1901, 2304CC1902, ...": "उदाहरण: माँ Cinta Senese पहचान संख्या 392019 + पिता Cinta Senese + ब्यांत 22/04/2023 → लॉट कोड 2304CC19। इकाइयाँ: 2304CC1901, 2304CC1902, ...",
"Registrare un parto suini dalla sezione Lotti": "लॉट हिस्से से सूअरों का ब्यांत दर्ज करना",
"Vai in 🐷 Lotti → '+ Nuovo parto'": "🐷 लॉट → '+ नया ब्यांत' पर जाएँ",
"Scegli madre e padre → il codice lotto appare subito automaticamente": "माँ और पिता चुनें → लॉट कोड तुरंत दिखता है",
"Inserisci data parto, nati totali, nati morti → i vivi si calcolano": "ब्यांत की तारीख, कुल जन्मे, मरे हुए जन्मे डालें → ज़िंदा अपने आप गिने जाते हैं",
"Facoltativo: data accoppiamento → calcola data prevista parto (+3 mesi +3 sett. +3 giorni)": "वैकल्पिक: मिलन की तारीख → अनुमानित ब्यांत तारीख निकालता है (+3 महीने +3 हफ़्ते +3 दिन)",
"Tocca 'Registra parto e crea lotto'": "'ब्यांत दर्ज करें और लॉट बनाएँ' दबाएँ",
"L'app crea il lotto + N unità (una per ogni nato vivo) + evento riproduttivo sulla madre": "ऐप लॉट + N इकाइयाँ (हर ज़िंदा बच्चे के लिए एक) + माँ पर प्रजनन घटना बनाता है",
"Gestire le unità di un lotto": "लॉट की इकाइयों को संभालना",
"Tocca un lotto nella lista → si apre la scheda con tutte le unità": "सूची में किसी लॉट को दबाएँ → सभी इकाइयों के साथ उसका रिकॉर्ड खुलता है",
"Cerca per tatuaggio completo (es. 2304CC1901) o parziale": "पूरे टैटू (जैसे 2304CC1901) या उसके हिस्से से खोजें",
"Su ogni unità (✏️): assegna sesso, destinazione (ingrasso / riproduzione / macello), matricola individuale": "हर इकाई पर (✏️): लिंग, उद्देश्य (मोटा करना / प्रजनन / वध), व्यक्तिगत पहचान संख्या तय करें",
"Pulsante 📤 per registrare uscita: motivo, data, peso vivo, peso carcassa, resa % calcolata": "निकासी दर्ज करने के लिए 📤 बटन: कारण, तारीख, जीवित वज़न, शव का वज़न, गणना की गई उपज %",
"La scheda lotto mostra in sintesi: vivi / macellati / deceduti / riproduttori / maschi / femmine": "लॉट रिकॉर्ड में सारांश: ज़िंदा / वध किए गए / मरे / प्रजनक / नर / मादा",
"Trovare un suinetto per tatuaggio": "टैटू से सूअर का बच्चा खोजना",
"Nella lista lotti: usa la barra di ricerca in cima — digita il tatuaggio completo (es. 2304CC1901) o il codice lotto (es. 2304CC19) per trovare subito l'unità.": "लॉट सूची में ऊपर खोज पट्टी का उपयोग करें — इकाई तुरंत खोजने के लिए पूरा टैटू (जैसे 2304CC1901) या लॉट कोड (जैसे 2304CC19) लिखें।",
"Registro sanitario": "स्वास्थ्य रजिस्टर",
"Tre modalità di registrazione": "दर्ज करने के तीन तरीके",
"+ Singolo": "+ एक पशु",
"Un singolo animale — apri, compila, salva": "केवल एक पशु — खोलें, भरें, सहेजें",
"💉 Gruppo": "💉 समूह",
"Più animali dell'anagrafica (bovini, ovini, suini con matricola) — selezione multipla con spunte": "रजिस्टर के कई पशु (गाय-बैल, भेड़, पहचान संख्या वाले सूअर) — टिक लगाकर कई चुनें",
"🐷 Lotto": "🐷 लॉट",
"Suinetti di un lotto specifico — selezione per lotto poi per unità": "किसी एक लॉट के सूअर के बच्चे — पहले लॉट चुनें, फिर इकाइयाँ",
"Evento di gruppo": "समूह घटना",
"Tocca '💉 Gruppo'": "'💉 समूह' दबाएँ",
"STEP 1: seleziona gli animali con le spunte (cerca per BDN, ultime 4 cifre o nome)": "चरण 1: टिक लगाकर पशु चुनें (BDN, आख़िरी 4 अंक या नाम से खोजें)",
"Usa 'Seleziona tutti' per trattare l'intera mandria": "पूरे झुंड के इलाज के लिए 'सब चुनें' का उपयोग करें",
"STEP 2: compila tipo, descrizione, prodotto, veterinario, data, costo totale": "चरण 2: प्रकार, विवरण, दवा/उत्पाद, पशु-चिकित्सक, तारीख, कुल लागत भरें",
"Il costo viene diviso automaticamente per il numero di animali": "लागत अपने आप पशुओं की संख्या से बँट जाती है",
"Tocca 'Registra evento su N animali'": "'N पशुओं पर घटना दर्ज करें' दबाएँ",
"Trattamento su lotto suini": "सूअर के लॉट पर इलाज",
"Tocca '🐷 Lotto'": "'🐷 लॉट' दबाएँ",
"STEP 1: scegli il lotto dalla lista (cerca per codice lotto)": "चरण 1: सूची से लॉट चुनें (लॉट कोड से खोजें)",
"Seleziona le unità da trattare (o 'Seleziona tutte le vive')": "इलाज वाली इकाइयाँ चुनें (या 'सभी ज़िंदा चुनें')",
"STEP 2: compila i dati del trattamento": "चरण 2: इलाज का डेटा भरें",
"Tocca 'Registra trattamento su N unità'": "'N इकाइयों पर इलाज दर्ज करें' दबाएँ",
"Ricerca eventi": "घटनाएँ खोजना",
"Usa la barra di ricerca in cima: cerca per BDN, ultime 4 cifre, nome animale, tipo evento o prodotto farmaceutico.": "ऊपर खोज पट्टी का उपयोग करें: BDN, आख़िरी 4 अंक, पशु का नाम, घटना का प्रकार या दवा से खोजें।",
"Le vaccinazioni compaiono automaticamente nella scheda di ogni animale (tab 📋 Info → sezione Vaccinazioni).": "टीके हर पशु के रिकॉर्ड में अपने आप दिखते हैं (📋 जानकारी टैब → टीकाकरण भाग)।",
"Alimentazione": "आहार",
"Due modalità": "दो तरीके",
"Razione per un singolo animale o specie": "एक पशु या एक प्रजाति के लिए राशन",
"🌾 Gruppo": "🌾 समूह",
"Stessa razione su più animali con selezione multipla": "कई चुने हुए पशुओं को एक ही राशन",
"Razione di gruppo": "समूह राशन",
"Tocca '🌾 Gruppo'": "'🌾 समूह' दबाएँ",
"STEP 1: seleziona gli animali": "चरण 1: पशु चुनें",
"STEP 2: tipo mangime, quantità PER CAPO, unità, data, costo totale": "चरण 2: चारे का प्रकार, प्रति पशु मात्रा, इकाई, तारीख, कुल लागत",
"Il costo viene diviso per i capi — vedi anteprima quantità totale (es. 3 kg × 45 = 135 kg)": "लागत पशुओं की संख्या से बँटती है — कुल मात्रा का पूर्वावलोकन देखें (जैसे 3 kg × 45 = 135 kg)",
"Tocca 'Registra razione su N animali'": "'N पशुओं पर राशन दर्ज करें' दबाएँ",
"Pesate — lo storico dei pesi": "वज़न — वज़न का इतिहास",
"Prima c'era un solo campo 'peso attuale' che si sovrascriveva a ogni aggiornamento: della pesata precedente non restava traccia. Ora ogni pesata è una riga a sé, e la storia dell'animale resta tutta.": "पहले केवल एक 'वर्तमान वज़न' फ़ील्ड था जो हर बार ऊपर लिखा जाता था: पिछले वज़न का कोई निशान नहीं बचता था। अब हर वज़न अलग पंक्ति है, और पशु का पूरा इतिहास बचा रहता है।",
"Registrare una pesata": "वज़न दर्ज करना",
"Apri la scheda dell'animale → tab ⚖️ Pesate": "पशु का रिकॉर्ड खोलें → ⚖️ वज़न टैब",
"Tocca '+ Registra pesata'": "'+ वज़न दर्ज करें' दबाएँ",
"Inserisci data e peso in kg": "तारीख और kg में वज़न डालें",
"Scegli il tipo di rilevazione (vedi tabella sotto)": "माप का प्रकार चुनें (नीचे तालिका देखें)",
"Salva — la riga compare nell'elenco, eliminabile con 🗑️ se hai sbagliato": "सहेजें — पंक्ति सूची में दिखती है; गलती हो तो 🗑️ से मिटा सकते हैं",
"I tipi di rilevazione": "माप के प्रकार",
"Nascita": "जन्म",
"Peso alla nascita": "जन्म के समय वज़न",
"Ingresso": "आगमन",
"Peso rilevato quando l'animale entra in azienda — importante per gli acquistati, di cui non conosciamo il peso di nascita vero": "पशु के फ़ार्म पर आने के समय लिया गया वज़न — खरीदे गए पशुओं के लिए ज़रूरी, जिनका असली जन्म वज़न हमें पता नहीं",
"In vita": "जीवित",
"Una pesata qualsiasi durante l'allevamento": "पालन के दौरान कोई भी वज़न",
"Uscita vivo": "जीवित निकासी",
"Peso vivo al momento dell'uscita": "निकासी के समय जीवित वज़न",
"Uscita carcassa": "शव निकासी",
"Peso della carcassa dal referto del macello": "बूचड़खाने की रिपोर्ट से शव का वज़न",
"La spunta 'stimato'": "'अनुमानित' टिक",
"Serve a distinguere un peso REALE da uno messo per convenzione. Quando un animale è stato acquistato e il peso di nascita non si conosce, si usa lo standard di specie (45 kg bovino, 0,5 kg suino, 2 kg ovino) e si spunta 'stimato'. Così chi legge i dati sa che quel numero non è stato misurato.": "यह असली वज़न को नियम से डाले गए वज़न से अलग करता है। जब पशु खरीदा गया हो और जन्म वज़न पता न हो, तो प्रजाति का मानक वज़न डाला जाता है (गाय-बैल 45 kg, सूअर 0,5 kg, भेड़ 2 kg) और 'अनुमानित' पर टिक लगाया जाता है। इससे पढ़ने वाला जानता है कि यह संख्या नापी नहीं गई।",
"Perché ha senso pesare spesso: la Contabilità Industriale userà tutti questi punti data/peso per stimare l'accrescimento e il costo al kg per fascia di età. Più pesate reali ci sono, più quella stima è affidabile — e i pesi si accumulano solo se qualcuno li registra.": "बार-बार वज़न लेना क्यों अच्छा है: लागत लेखा इन सभी तारीख/वज़न बिंदुओं से बढ़त और उम्र के वर्ग के अनुसार प्रति kg लागत का अनुमान लगाएगा। जितने ज़्यादा असली वज़न होंगे, अनुमान उतना भरोसेमंद होगा — और वज़न तभी जुड़ते हैं जब कोई उन्हें दर्ज करे।",
"Coltivazione — campi, colture, costi e report": "खेती — खेत, फ़सलें, लागत और रिपोर्ट",
"La sezione 🌾 Coltivazione raccoglie i campi aziendali (16 in uso oggi, 84,43 ettari, più quelli coltivati negli anni passati) con foto aerea e dati catastali, e tutto quello che ci si fa sopra campagna per campagna: colture, semine, lavorazioni, concimi, raccolte, costi e risultati.": "🌾 खेती हिस्से में फ़ार्म के खेत हैं (आज 16 उपयोग में, 84,43 हेक्टेयर, और पिछले वर्षों में जोते गए खेत भी) हवाई फ़ोटो और भूमि-रिकॉर्ड के साथ, और हर मौसम में उन पर किया गया सब काम: फ़सलें, बुवाई, खेत के काम, खाद, कटाई, लागत और परिणाम।",
"La campagna agraria — si sceglie in cima": "कृषि मौसम — ऊपर चुना जाता है",
"Il selettore in alto comanda l'intera sezione: cambiando campagna cambia tutto quello che vedi sotto. La campagna va dal 1° settembre al 31 agosto: la semina d'autunno e la trebbiatura dell'estate dopo stanno nella stessa campagna, e anche le semine di primavera-estate (pascoli, erbai in irriguo) appartengono alla campagna iniziata il settembre precedente. Si arriva indietro fino al 2019/2020; la 2022/2023 non è caricata.": "ऊपर का चयनकर्ता पूरे हिस्से को चलाता है: मौसम बदलने से नीचे सब कुछ बदल जाता है। मौसम 1 सितंबर से 31 अगस्त तक चलता है: शरद की बुवाई और अगली गर्मी की थ्रेशिंग एक ही मौसम में आती हैं, और वसंत-गर्मी की बुवाई (चरागाह, सिंचित चारा फ़सलें) भी पिछले सितंबर में शुरू हुए मौसम की होती है। आप 2019/2020 तक पीछे जा सकते हैं; 2022/2023 दर्ज नहीं है।",
"Le cinque linguette": "पाँच टैब",
"🗺️ Campi": "🗺️ खेत",
"Lista dei campi e scheda di ogni campo: si registra qui": "खेतों की सूची और हर खेत का रिकॉर्ड: यहीं दर्ज किया जाता है",
"📊 Riepilogo": "📊 सारांश",
"Ettari, giornate di lavoro, quantità e rese della campagna, per coltura": "मौसम के हेक्टेयर, काम के दिन, मात्रा और उपज, फ़सल के अनुसार",
"🗓️ Programma": "🗓️ योजना",
"Cosa seminare e concimare in ogni campo, e cosa comprare": "हर खेत में क्या बोना और कौन सी खाद डालनी है, और क्या खरीदना है",
"📈 Report": "📈 रिपोर्ट",
"Costi, valore di mercato e rese della campagna scelta": "चुने गए मौसम की लागत, बाज़ार मूल्य और उपज",
"📚 Storico": "📚 इतिहास",
"Tutte le stagioni insieme: per coltura, per campo e classifiche": "सभी मौसम एक साथ: फ़सल के अनुसार, खेत के अनुसार और रैंकिंग",
"🗺️ Campi — la scheda del campo": "🗺️ खेत — खेत का रिकॉर्ड",
"Tocca un campo: si apre la scheda con le colture della campagna": "किसी खेत को दबाएँ: मौसम की फ़सलों के साथ उसका रिकॉर्ड खुलता है",
"Per metterne una nuova tocca '+ Aggiungi coltura' e scegli fra Avena, Erba Medica, Erbaio Misto, Grano, Orzo, Pisello Proteico, Produzione Seme, Sulla — oppure 'Altro' e scrivi il nome": "नई फ़सल जोड़ने के लिए '+ फ़सल जोड़ें' दबाएँ और चुनें: जई, रिज़का (अल्फ़ाल्फ़ा), मिश्रित चारा फ़सल, गेहूँ, जौ, प्रोटीन मटर, बीज उत्पादन, सुल्ला — या 'अन्य' चुनकर नाम लिखें",
"Per medica e sulla, che sono poliennali, indica in quale campagna sono state seminate: nelle campagne dopo la semina non viene più chiesta": "रिज़का और सुल्ला कई साल चलने वाली फ़सलें हैं: बताएँ कि उन्हें किस मौसम में बोया गया था; बाद के मौसमों में बुवाई नहीं पूछी जाती",
"Salva — compare il blocco della coltura con tre linguette: Semina, Lavorazioni, Raccolta": "सहेजें — फ़सल का खाना तीन टैब के साथ दिखता है: बुवाई, खेत के काम, कटाई",
"Sullo stesso campo puoi mettere PIÙ colture nella stessa campagna: le successioni (orzo mietuto a giugno e poi un erbaio estivo, o il sorgo dopo il pascolo) e le porzioni di campo con colture diverse. Basta premere di nuovo '+ Aggiungi coltura'.": "एक ही खेत पर एक ही मौसम में कई फ़सलें रखी जा सकती हैं: एक के बाद एक फ़सलें (जून में जौ कटने के बाद गर्मी की चारा फ़सल, या चराई के बाद ज्वार) और खेत के अलग-अलग हिस्सों में अलग फ़सलें। बस फिर से '+ फ़सल जोड़ें' दबाएँ।",
"🌱 Semina": "🌱 बुवाई",
"Nel menu 'Seme' compaiono per primi, con 📋, i semi previsti dal Programma per quella coltura; sotto, tutti i semi già usati in azienda. Se manca, scegli '✏️ Altro seme' e scrivi il nome": "'बीज' मेनू में सबसे पहले 📋 के साथ उस फ़सल के लिए योजना में तय बीज आते हैं; उनके नीचे फ़ार्म पर पहले इस्तेमाल हुए सभी बीज। अगर बीज सूची में नहीं है, तो '✏️ अन्य बीज' चुनकर नाम लिखें",
"Inserisci la quantità in quintali: l'app calcola da sola i chilogrammi, i quintali per ettaro e i chilogrammi per ettaro sugli ettari della coltura": "मात्रा क्विंटल में डालें (1 क्विंटल = 100 kg): ऐप फ़सल के हेक्टेयर पर किलोग्राम, प्रति हेक्टेयर क्विंटल और प्रति हेक्टेयर किलोग्राम अपने आप निकालता है",
"Per GRANO e ORZO puoi usare le 'dosi' (confezioni) al posto dei quintali: in quel caso calcola le dosi per ettaro": "गेहूँ और जौ के लिए क्विंटल की जगह 'डोज़' (बोरी/पैकेट) का उपयोग कर सकते हैं: तब ऐप प्रति हेक्टेयर डोज़ निकालता है",
"Per ERBAIO MISTO e PRODUZIONE SEME registra una riga per ciascuna essenza (trifoglio, avena, loietto) con '+ Aggiungi seme'": "मिश्रित चारा फ़सल और बीज उत्पादन के लिए हर किस्म (तिपतिया घास, जई, राईघास) की अलग पंक्ति '+ बीज जोड़ें' से दर्ज करें",
"🚜 Lavorazioni": "🚜 खेत के काम",
"L'elenco delle 15 lavorazioni è sempre lì: aratura, estirpatura, erpicatura, morganatura, rippatura, spietratura, concimazione, semina, disserbo, sfalcio, ranghinatura, pressatura balle, raccolta balle, trebbiatura, irrigazione.": "15 खेत के कामों की सूची हमेशा दिखती है: जुताई, कल्टीवेटर, हैरो, डिस्क हैरो, गहरी जुताई (रिपर), पत्थर हटाना, खाद डालना, बुवाई, खरपतवार नाशक छिड़काव, कटाई (घास), घास समेटना, गट्ठर बनाना, गट्ठर उठाना, थ्रेशिंग, सिंचाई।",
"Tocca la riga della lavorazione eseguita — si apre": "किए गए काम की पंक्ति दबाएँ — वह खुल जाती है",
"Tocca 'Registra esecuzione'": "'काम दर्ज करें' दबाएँ",
"Metti la data e le giornate di lavoro impiegate — anche mezze giornate, si scrive 0,5": "तारीख और लगे काम के दिन डालें — आधा दिन भी, 0,5 लिखें",
"Salva: la spunta della riga diventa verde": "सहेजें: पंक्ति का निशान हरा हो जाता है",
"La stessa lavorazione si registra più volte: la medica si sfalcia 3-4 volte l'anno e l'irrigazione si ripete per tutta l'estate. Ogni volta aggiungi una nuova esecuzione con la sua data e le sue giornate: accanto al nome compare ×3 e le giornate si sommano.": "एक ही काम कई बार दर्ज होता है: रिज़का साल में 3-4 बार कटता है और सिंचाई पूरी गर्मी चलती है। हर बार अपनी तारीख और दिनों के साथ नया काम जोड़ें: नाम के पास ×3 दिखेगा और दिन जुड़ जाएँगे।",
"CONCIMAZIONE: il form chiede quali concimi — binario, ternario, stallatico, letame o altro — e i quintali di ciascuno; se ne possono mettere più di uno nella stessa passata": "खाद डालना: फ़ॉर्म पूछता है कौन सी खाद — बाइनरी, टर्नरी, गोबर खाद, सड़ी खाद या अन्य — और हर एक कितने क्विंटल; एक ही बार में एक से ज़्यादा खाद डाल सकते हैं",
"DISSERBO: il form chiede il prodotto, la quantità e se è in litri o in chilogrammi": "खरपतवार नाशक: फ़ॉर्म दवा का नाम, मात्रा और लीटर या किलोग्राम पूछता है",
"La quantità per ettaro si calcola da sola sugli ettari della coltura": "प्रति हेक्टेयर मात्रा फ़सल के हेक्टेयर पर अपने आप निकलती है",
"🌾 Raccolta": "🌾 कटाई",
"Linguetta Raccolta → '+ Registra raccolta'": "कटाई टैब → '+ कटाई दर्ज करें'",
"Scegli il PRODOTTO raccolto (non la coltura): avena, erba medica, erbaio misto, grano, orzo, paglia, pisello proteico, sulla, seme misto, seme di medica, seme di sulla, o Altro": "काटा गया उत्पाद चुनें (फ़सल नहीं): जई, रिज़का, मिश्रित चारा, गेहूँ, जौ, भूसा, प्रोटीन मटर, सुल्ला, मिश्रित बीज, रिज़का बीज, सुल्ला बीज, या अन्य",
"L'unità si imposta da sola — quintali per i cereali, balloni per i foraggi — ma puoi cambiarla in quintali, balloni, rotoballe o chilogrammi": "इकाई अपने आप लगती है — अनाज के लिए क्विंटल, चारे के लिए गट्ठर — पर आप इसे क्विंटल, गट्ठर, गोल गट्ठर या किलोग्राम में बदल सकते हैं",
"Inserisci la quantità e la data: la resa per ettaro si calcola da sola": "मात्रा और तारीख डालें: प्रति हेक्टेयर उपज अपने आप निकलती है",
"PAGLIA, SEME DI MEDICA e SEME DI SULLA sono sottoprodotti: escono dagli stessi ettari della coltura principale e nel riepilogo non ne raddoppiano ettari e giornate. Le colture PASCOLATE non hanno raccolta: il loro costo va tutto al pascolo.": "भूसा, रिज़का बीज और सुल्ला बीज उप-उत्पाद हैं: ये मुख्य फ़सल के उन्हीं हेक्टेयर से आते हैं, और सारांश में हेक्टेयर और काम के दिन दो बार नहीं गिने जाते। चराई वाली फ़सलों की कटाई नहीं होती: उनकी पूरी लागत चराई में जाती है।",
"✏️ Correggere un dato": "✏️ गलत दर्ज जानकारी ठीक करना",
"Le esecuzioni delle lavorazioni e le raccolte si correggono o si cancellano con la matita e il cestino accanto alla riga: ognuno può farlo sulle righe inserite da lui, entro 48 ore dall'inserimento. Dopo, o per le righe di altri, serve l'amministratore. Una riga corretta mostra '✏️ Corretto il…' e il valore di prima resta nello storico delle rettifiche.": "खेत के काम और कटाई पंक्ति के पास पेंसिल और कूड़ेदान से ठीक की या मिटाई जा सकती हैं: हर कोई अपनी दर्ज की हुई पंक्तियों पर, दर्ज करने के 48 घंटे के भीतर ऐसा कर सकता है। उसके बाद, या दूसरों की पंक्तियों के लिए, व्यवस्थापक (एडमिन) चाहिए। ठीक की गई पंक्ति पर '✏️ ठीक किया गया…' दिखता है और पुराना मान सुधारों के इतिहास में रहता है।",
"Tutti i campi della campagna raggruppati per coltura: ettari dedicati, giornate di lavoro e, per ciascun prodotto, quantità raccolta, resa per ettaro e resa per giornata di lavoro. Si compila da solo man mano che si inseriscono i dati.": "मौसम के सभी खेत फ़सल के अनुसार: लगे हेक्टेयर, काम के दिन और हर उत्पाद के लिए काटी गई मात्रा, प्रति हेक्टेयर उपज और प्रति काम-दिवस उपज। डेटा डालते ही यह अपने आप भरता है।",
"🗺️ Per campo: per ogni coltura i semi e i concimi previsti, con dose per ettaro e quantità totale (dose × ettari); le confezioni sono arrotondate per eccesso. Sotto, '▸ Istruzioni per semina e concimazione' apre le note del piano approvato": "🗺️ खेत के अनुसार: हर फ़सल के लिए तय बीज और खाद, प्रति हेक्टेयर मात्रा और कुल मात्रा (मात्रा × हेक्टेयर) के साथ; पैकेट ऊपर की ओर पूरे किए जाते हैं। नीचे '▸ बुवाई और खाद के निर्देश' स्वीकृत योजना के नोट खोलता है",
"🛒 Da acquistare: gli stessi prodotti sommati su tutta l'azienda, cioè la lista della spesa della campagna": "🛒 खरीदना है: वही उत्पाद पूरे फ़ार्म के लिए जोड़कर, यानी मौसम की खरीद सूची",
"Il programma lo prepara l'amministratore dal piano approvato dal dott. Bizzarri; chi semina trova i semi previsti già proposti nel menu della Semina": "योजना व्यवस्थापक डॉ. Bizzarri द्वारा स्वीकृत योजना से बनाता है; बोने वाले को तय बीज बुवाई मेनू में पहले से दिखते हैं",
"📈 Report — la campagna scelta": "📈 रिपोर्ट — चुना गया मौसम",
"Il costo di ogni coltura è semi + concimi + fitosanitari + lavorazioni + altro, dalle schede campo approvate. Le lavorazioni fatte in azienda sono valutate a tariffa, senza fattura. Il costo della coltura si divide fra tutti i suoi prodotti (paglia e seme compresi) in proporzione al valore di mercato.": "हर फ़सल की लागत है बीज + खाद + फ़सल सुरक्षा दवाएँ + खेत के काम + अन्य, स्वीकृत खेत रिकॉर्ड से। फ़ार्म के अपने किए काम बिना बिल के तय दर पर गिने जाते हैं। फ़सल की लागत उसके सभी उत्पादों (भूसा और बीज भी) में बाज़ार मूल्य के अनुपात में बाँटी जाती है।",
"In cima: superficie, costo totale, costo per ettaro e saldo contro il mercato": "ऊपर: क्षेत्रफल, कुल लागत, प्रति हेक्टेयर लागत और बाज़ार के मुकाबले शेष",
"DOVE GUADAGNI e DOVE PERDI: i prodotti che sono costati meno o più del loro prezzo di mercato, con il semaforo (verde sotto il mercato, giallo poco sopra, rosso oltre la soglia)": "कहाँ फ़ायदा और कहाँ नुकसान: वे उत्पाद जिनकी लागत बाज़ार भाव से कम या ज़्यादा रही, ट्रैफ़िक-लाइट के साथ (हरा बाज़ार से नीचे, पीला थोड़ा ऊपर, लाल सीमा से ऊपर)",
"RESE CONTRO IL RIFERIMENTO: la resa per ettaro confrontata con la media ISTAT della provincia di Roma, solo per orzo, avena e favino; per fieni, paglia, sementi e pascoli un riferimento affidabile non c'è": "संदर्भ के मुकाबले उपज: प्रति हेक्टेयर उपज की तुलना रोम प्रांत के ISTAT औसत से, केवल जौ, जई और बाकला के लिए; सूखी घास, भूसा, बीज और चरागाह के लिए भरोसेमंद संदर्भ नहीं है",
"PASCOLI: le colture pascolate senza raccolta, con il loro costo per ettaro": "चरागाह: बिना कटाई वाली चराई फ़सलें, प्रति हेक्टेयर लागत के साथ",
"COSTI PER COLTURA: tocca una coltura per vedere i suoi campi": "फ़सल के अनुसार लागत: उसके खेत देखने के लिए फ़सल दबाएँ",
"⚙️ Prezzi e rese: prezzi di mercato in euro al quintale, peso del ballone e della rotoballa (340 chilogrammi), soglia del semaforo e rese di riferimento. Li modifica solo l'amministratore; il report si ricalcola subito": "⚙️ भाव और उपज: प्रति क्विंटल यूरो में बाज़ार भाव, गट्ठर और गोल गट्ठर का वज़न (340 किलोग्राम), ट्रैफ़िक-लाइट की सीमा और संदर्भ उपज। इन्हें केवल व्यवस्थापक बदल सकता है; रिपोर्ट तुरंत दोबारा गणना करती है",
"📥 Esporta Excel e 📅 Confronto tra stagioni (tutte le stagioni affiancate: superficie, costo per ettaro, saldo e produzione)": "📥 Excel निर्यात और 📅 मौसमों की तुलना (सभी मौसम साथ-साथ: क्षेत्रफल, प्रति हेक्टेयर लागत, शेष और उत्पादन)",
"📚 Storico — tutte le stagioni": "📚 इतिहास — सभी मौसम",
"🌱 Per coltura": "🌱 फ़सल के अनुसार",
"Stagione per stagione: ettari, resa, costo e costo di ogni unità di prodotto contro il mercato": "मौसम-दर-मौसम: हेक्टेयर, उपज, लागत और बाज़ार के मुकाबले उत्पाद की हर इकाई की लागत",
"🗺️ Per campo": "🗺️ खेत के अनुसार",
"Per un campo: coltura, produzione, costi, concimi con la dose per ettaro e risultato contro il mercato": "एक खेत के लिए: फ़सल, उत्पादन, लागत, प्रति हेक्टेयर मात्रा के साथ खाद और बाज़ार के मुकाबले परिणाम",
"🏅 Ranking stagione": "🏅 मौसम रैंकिंग",
"In ogni stagione i campi dal migliore al peggiore per costo del prodotto rapportato al prezzo di mercato": "हर मौसम में खेत सबसे अच्छे से सबसे खराब तक, उत्पाद की लागत को बाज़ार भाव से मिलाकर",
"🏆 Ranking resa": "🏆 उपज रैंकिंग",
"I campi su tutte le stagioni, confrontati con gli altri della stessa coltura: 100 = media dell'azienda": "सभी मौसमों के खेत, उसी फ़सल वाले दूसरे खेतों से तुलना: 100 = फ़ार्म का औसत",
"🥇 Ranking per coltura": "🥇 फ़सल के अनुसार रैंकिंग",
"Per una coltura, i campi che l'hanno avuta sommando tutte le stagioni, al quintale del prodotto principale": "एक फ़सल के लिए, जिन खेतों में वह रही, सभी मौसम जोड़कर, मुख्य उत्पाद के प्रति क्विंटल",
"Report e Storico non si compilano: si ricalcolano ogni volta dai dati del database. Se si corregge una scheda, un prezzo o una resa, cambiano subito. Esclusi i pascoli, che non hanno un prodotto misurato.": "रिपोर्ट और इतिहास भरे नहीं जाते: हर बार डेटाबेस से दोबारा गणना होती है। अगर कोई रिकॉर्ड, भाव या उपज ठीक की जाए, तो वे तुरंत बदल जाते हैं। चरागाह शामिल नहीं हैं, क्योंकि उनका कोई नापा हुआ उत्पाद नहीं है।",
"🏭 Collegamento con la Contabilità Industriale": "🏭 लागत लेखा से जुड़ाव",
"La Contabilità Industriale legge, in sola lettura, gli stessi dati delle coltivazioni attraverso le viste del database, e trova i report Excel delle coltivazioni (rese delle stagioni, schede campo, piano della campagna) nell'archivio dei report, sempre all'ultima versione. Dall'app Coltivazione non si scrive mai nei dati della Contabilità Industriale.": "लागत लेखा खेती का वही डेटा डेटाबेस के व्यू से केवल पढ़ता है, और खेती की Excel रिपोर्टें (मौसमों की उपज, खेत रिकॉर्ड, मौसम की योजना) रिपोर्ट संग्रह में हमेशा नवीनतम संस्करण में पाता है। खेती ऐप कभी भी लागत लेखा के डेटा में नहीं लिखता।",
"Registro uscite": "निकासी रजिस्टर",
"Come registrare un'uscita": "निकासी कैसे दर्ज करें",
"Vai in 📤 Uscite": "📤 निकासी पर जाएँ",
"Usa i filtri specie (bovini / suini / ovini) per restringere la lista": "सूची छोटी करने के लिए प्रजाति फ़िल्टर (गाय-बैल / सूअर / भेड़) का उपयोग करें",
"Cerca per BDN, ultime 4 cifre, nome, lotto o razza": "BDN, आख़िरी 4 अंक, नाम, लॉट या नस्ल से खोजें",
"Tab 'In stalla': trova l'animale → tocca '📤 Uscita'": "'बाड़े में' टैब: पशु खोजें → '📤 निकासी' दबाएँ",
"Scegli motivo, data, peso vivo": "कारण, तारीख, जीवित वज़न चुनें",
"Se macellato: inserisci peso carcassa → resa % calcolata automaticamente": "अगर वध हुआ: शव का वज़न डालें → उपज % अपने आप निकलती है",
"I giorni di permanenza in stalla vengono calcolati automaticamente": "फ़ार्म पर बिताए दिन अपने आप गिने जाते हैं",
"Tocca 'Registra uscita'": "'निकासी दर्ज करें' दबाएँ",
"Tipi di uscita": "निकासी के प्रकार",
"🔪 Macellato — con peso vivo, peso carcassa, resa %": "🔪 वध — जीवित वज़न, शव का वज़न, उपज % के साथ",
"✝️ Morto (cause naturali o malattia)": "✝️ मृत (प्राकृतिक कारण या बीमारी)",
"💰 Venduto vivo": "💰 जीवित बेचा",
"🚨 Furto · 🏃 Scappato · 🔄 Trasferito": "🚨 चोरी · 🏃 भाग गया · 🔄 स्थानांतरित",
"Tab 'Usciti'": "'निकले हुए' टैब",
"Storico di tutti gli animali usciti con filtro per specie. Mostra riepilogo macellazioni: peso vivo totale, carcassa totale, resa media.": "प्रजाति फ़िल्टर के साथ सभी निकले पशुओं का इतिहास। वध का सारांश दिखाता है: कुल जीवित वज़न, कुल शव, औसत उपज।",
"Pedigree e genealogia": "वंशावली और वंश",
"Il modulo Pedigree legge automaticamente i dati genealogici delle schede. Non serve inserire nulla in più.": "वंशावली मॉड्यूल रिकॉर्ड से वंश की जानकारी अपने आप पढ़ता है। कुछ अलग से डालने की ज़रूरत नहीं।",
"Albero visuale a 3 generazioni (soggetto → genitori → nonni)": "3 पीढ़ियों का चित्र-वृक्ष (पशु → माता-पिता → दादा-दादी/नाना-नानी)",
"Nodi cliccabili: tocca un antenato per aprirne la scheda": "क्लिक होने वाले खाने: किसी पूर्वज को दबाकर उसका रिकॉर्ड खोलें",
"Badge 'pedigree ✓' sugli animali con genealogia tracciata": "जिन पशुओं का वंश दर्ज है उन पर 'pedigree ✓' बैज",
"Storico parti con nati vivi/morti": "ज़िंदा/मरे जन्मों के साथ ब्यांत का इतिहास",
"Discendenti diretti con link alle schede": "सीधी संतानें, उनके रिकॉर्ड के लिंक के साथ",
"Per un albero completo, collega sempre padre e madre nella scheda di ogni animale.": "पूरे वृक्ष के लिए हर पशु के रिकॉर्ड में हमेशा पिता और माता जोड़ें।",
"Selezione genetica": "आनुवंशिक चयन",
"KPI calcolati automaticamente": "अपने आप गणना होने वाले संकेतक",
"N° parti": "ब्यांतों की संख्या",
"Totale parti registrati per femmina": "हर मादा के कुल दर्ज ब्यांत",
"IIP medio": "औसत ब्यांत अंतराल",
"Intervallo inter-parto in giorni E mesi (meno = meglio)": "दो ब्यांतों के बीच का समय दिनों और महीनों में (कम = बेहतर)",
"% nati vivi": "% ज़िंदा जन्मे",
"Nati vivi su totale nati": "कुल जन्मों में से ज़िंदा जन्मे",
"Prolificità": "प्रजनन क्षमता",
"Media nati vivi per parto": "हर ब्यांत में औसत ज़िंदा जन्मे",
"Longevità": "दीर्घायु",
"Anni di carriera riproduttiva": "प्रजनन के वर्ष",
"Massimizzare l'accuratezza del ranking": "रैंकिंग को सबसे सटीक बनाना",
"Registra TUTTI i parti (presenti e storici) nella scheda di ogni fattrice": "हर प्रजनक मादा के रिकॉर्ड में सभी ब्यांत (नए और पुराने) दर्ज करें",
"Per parti storici usa '📅 Parto storico' — bastano data, totali, morti": "पुराने ब्यांतों के लिए '📅 पुराना ब्यांत' का उपयोग करें — तारीख, कुल और मरे हुए काफ़ी हैं",
"Più parti hai registrati, più accurato è il ranking": "जितने ज़्यादा ब्यांत दर्ज होंगे, रैंकिंग उतनी सटीक होगी",
"Il ranking si aggiorna in tempo reale appena aggiungi nuovi eventi": "नई घटनाएँ जोड़ते ही रैंकिंग तुरंत अपडेट होती है",
"Costi — dove si guardano adesso": "लागत — अब कहाँ देखें",
"L'analisi economica è passata al programma di Contabilità Industriale, che lavora sullo stesso database di questa app ed è usato dai contabili. Qui dentro restano le due cose che servono a chi sta in allevamento.": "आर्थिक विश्लेषण अब लागत लेखा प्रोग्राम में होता है, जो इसी ऐप के डेटाबेस पर काम करता है और लेखाकार उसका उपयोग करते हैं। यहाँ पशुओं के साथ काम करने वालों के लिए दो चीज़ें बची हैं।",
"💰 Costi nella scheda dell'animale": "💰 पशु के रिकॉर्ड में लागत",
"Apri un animale → tab 💰 Costi. Vedi anno per anno: UBA-giorni, categoria contabile, costo di mantenimento, costo di nascita ereditato, quota già scaricata sui figli e totale dell'anno, con il cumulato in fondo.": "पशु खोलें → 💰 लागत टैब। साल-दर-साल दिखता है: पशु-इकाई-दिन, लेखा श्रेणी, रखरखाव लागत, विरासत में मिली जन्म लागत, संतानों पर डाला गया हिस्सा और साल का कुल, नीचे कुल जोड़ के साथ।",
"Questi numeri li CALCOLA la Contabilità Industriale, qui si leggono soltanto. Se un valore è sbagliato non si corregge da qui: si corregge là.": "ये आँकड़े लागत लेखा गणना करता है, यहाँ केवल पढ़े जाते हैं। अगर कोई मान गलत है तो यहाँ से ठीक नहीं होता: वहाँ ठीक होता है।",
"⚠️ Manca costo acquisto": "⚠️ खरीद लागत नहीं है",
"Se un animale ha provenienza 'Acquistato' ma il prezzo di acquisto è vuoto, compare un badge rosso sulla sua card in Anagrafica e un avviso in cima alla scheda. Serve perché un capo comprato senza prezzo falsa tutti i conti a valle.": "अगर किसी पशु की उत्पत्ति 'खरीदा गया' है पर खरीद मूल्य खाली है, तो रजिस्टर में उसके कार्ड पर लाल बैज और रिकॉर्ड के ऊपर चेतावनी दिखती है। यह ज़रूरी है क्योंकि बिना मूल्य के खरीदा पशु आगे के सारे हिसाब बिगाड़ देता है।",
"Per sistemarlo: apri la scheda → ✏️ Modifica → compila Prezzo acquisto → Salva": "ठीक करने के लिए: रिकॉर्ड खोलें → ✏️ बदलें → खरीद मूल्य भरें → सहेजें",
"Il campo è condiviso con la Contabilità Industriale: appena lo compili da una parte, l'avviso sparisce da entrambe": "यह फ़ील्ड लागत लेखा के साथ साझा है: एक जगह भरते ही चेतावनी दोनों जगह से हट जाती है",
"Le vecchie tab Costi, Origine e Struttura": "पुराने लागत, उत्पत्ति और ढाँचा टैब",
"Sono state tolte dalla barra perché quel lavoro si fa ora nella Contabilità Industriale. I dati non sono stati cancellati: macchinari, ammortamenti e costi generali sono tutti ancora nel database, e le tab si possono rimettere in qualsiasi momento.": "इन्हें पट्टी से हटाया गया क्योंकि यह काम अब लागत लेखा में होता है। कोई डेटा नहीं मिटाया गया: मशीनें, मूल्यह्रास और सामान्य लागत सब डेटाबेस में हैं, और टैब कभी भी वापस लगाए जा सकते हैं।",
"Storico aggiornamenti v29 → v64": "अपडेट का इतिहास v29 → v64",
"⚖️ Modifica peso carcassa su animali già usciti": "⚖️ निकल चुके पशुओं के शव का वज़न बदलना",
"Spesso passa del tempo tra il momento in cui un animale esce dall'allevamento (e un operatore registra data uscita e peso vivo) e il momento in cui arriva il referto del macello con il peso della carcassa (registrato magari da un altro operatore, giorni dopo).": "अक्सर पशु के फ़ार्म से निकलने (जब कर्मचारी निकासी की तारीख और जीवित वज़न दर्ज करता है) और बूचड़खाने से शव के वज़न की रिपोर्ट आने (शायद किसी दूसरे कर्मचारी द्वारा, कुछ दिन बाद) के बीच समय लगता है।",
"Apri la scheda dell'animale già uscito dall'Anagrafica (anche se il capo non è più attivo)": "रजिस्टर से निकल चुके पशु का रिकॉर्ड खोलें (भले ही पशु अब सक्रिय न हो)",
"Tocca Modifica e vai alla sezione Dati Uscita": "बदलें दबाएँ और निकासी डेटा भाग पर जाएँ",
"Inserisci o correggi il Peso carcassa (kg) in qualsiasi momento, anche mesi dopo": "शव का वज़न (kg) कभी भी डालें या ठीक करें, महीनों बाद भी",
"La Resa % (carcassa/peso vivo) si ricalcola automaticamente ogni volta che aggiorni il dato": "उपज % (शव / जीवित वज़न) हर बार आँकड़ा बदलने पर अपने आप दोबारा निकलती है",
"Utile per completare progressivamente la scheda man mano che arrivano i referti dal macello": "बूचड़खाने की रिपोर्टें आने के साथ रिकॉर्ड धीरे-धीरे पूरा करने के लिए उपयोगी",
"📮 Report Mensili automatici via Email": "📮 ईमेल से हर महीने अपने आप रिपोर्ट",
"Nuovo tab 📮 Email per gestire l'invio automatico di report e backup ai soggetti registrati (commercialista, direttore allevamento, consulenti, ecc.).": "नया 📮 ईमेल टैब — दर्ज लोगों (लेखाकार, फ़ार्म प्रबंधक, सलाहकार आदि) को रिपोर्ट और बैकअप अपने आप भेजने के लिए।",
"Registra destinatari con nome, email, ruolo e permessi (Report / Backup / Alert)": "प्राप्तकर्ता दर्ज करें — नाम, ईमेल, भूमिका और अनुमति (रिपोर्ट / बैकअप / चेतावनी) के साथ",
"Il 1° di ogni mese alle 06:00 il sistema invia automaticamente via email: report Excel (anagrafica, uscite del mese, sanitario) allegato a chi ha permesso Report": "हर महीने की 1 तारीख को सुबह 06:00 बजे सिस्टम अपने आप ईमेल भेजता है: रिपोर्ट अनुमति वालों को Excel रिपोर्ट (रजिस्टर, महीने की निकासी, स्वास्थ्य) संलग्न",
"Backup completo del database (file .sql) allegato a chi ha permesso Backup": "बैकअप अनुमति वालों को पूरे डेटाबेस का बैकअप (.sql फ़ाइल) संलग्न",
"Pulsante 🧪 Test invio per verificare il funzionamento in qualsiasi momento senza aspettare fine mese": "🧪 परीक्षण भेजें बटन — महीने के अंत का इंतज़ार किए बिना कभी भी जाँचने के लिए",
"Storico di tutti gli invii consultabile dal tab Email": "ईमेल टैब में सभी भेजे गए का इतिहास",
"🐾 Registro Sanitario — Filtri specie e scadenze": "🐾 स्वास्थ्य रजिस्टर — प्रजाति फ़िल्टर और नियत तारीखें",
"Filtro per specie (bovino/suino/ovino/tutti) nella registrazione singola e di gruppo — utile per vaccini specie-specifici": "एक पशु और समूह दोनों में प्रजाति फ़िल्टर (गाय-बैल/सूअर/भेड़/सभी) — प्रजाति-विशेष टीकों के लिए उपयोगी",
"Pulsante 🌾 Tutti per selezionare in un click tutti gli animali attivi dell'azienda": "🌾 सभी बटन — एक क्लिक में फ़ार्म के सभी सक्रिय पशु चुनने के लिए",
"11 tipi di evento sanitario (vaccino, richiamo, farmaco, antiparassitario, visita, intervento chirurgico, diagnostica, gravidanza, malattia, cura, altro)": "11 प्रकार की स्वास्थ्य घटनाएँ (टीका, बूस्टर, दवा, कृमिनाशक, जाँच, ऑपरेशन, निदान, गर्भ, बीमारी, इलाज, अन्य)",
"Box scadenze richiami in cima al Registro Sanitario (scaduti in rosso, imminenti 30gg in giallo)": "स्वास्थ्य रजिस्टर के ऊपर बूस्टर की नियत तारीखों का खाना (बीत चुके लाल में, 30 दिन के भीतर वाले पीले में)",
"Badge notifica sull'icona 💉 Salute nel menu con il numero di richiami da gestire": "मेनू में 💉 स्वास्थ्य आइकन पर सूचना बैज, संभालने वाले बूस्टरों की संख्या के साथ",
"Pulsante ✓ Registra su ogni scadenza per aprire il form già pre-compilato (nessuna registrazione automatica, sempre conferma manuale)": "हर नियत तारीख पर ✓ दर्ज करें बटन — पहले से भरा फ़ॉर्म खोलता है (कुछ भी अपने आप दर्ज नहीं होता, हमेशा हाथ से पुष्टि)",
"📅 Timeline eventi unificata nella scheda animale": "📅 पशु रिकॉर्ड में एक जगह सभी घटनाओं की समयरेखा",
"Nella scheda di ogni animale, il tab 📅 Eventi mostra ora una timeline cronologica che unisce nascita, ingresso, qualifica riproduttore, parti, eventi sanitari e uscita, con separatori per anno e statistiche riassuntive in cima.": "हर पशु के रिकॉर्ड में 📅 घटनाएँ टैब अब समय के क्रम में जन्म, आगमन, प्रजनक योग्यता, ब्यांत, स्वास्थ्य घटनाएँ और निकासी एक साथ दिखाता है, साल के अनुसार विभाजन और ऊपर सारांश आँकड़ों के साथ।",
"🐷 Lotti suini — Rifatti completamente": "🐷 सूअरों के लॉट — पूरी तरह नए सिरे से",
"Al salvataggio del parto suino, il lotto viene creato automaticamente nella sezione Lotti": "सूअर का ब्यांत सहेजते ही लॉट हिस्से में लॉट अपने आप बन जाता है",
"Nuovo pulsante 📦 Lotto acquistato — per registrare lotti comprati da terzi (fornitore, prezzo, N capi)": "नया 📦 खरीदा गया लॉट बटन — दूसरों से खरीदे लॉट दर्ज करने के लिए (आपूर्तिकर्ता, मूल्य, पशुओं की संख्या)",
"Ogni unità del lotto ha 2 pulsanti: 🏷️ BDN (assegna matricola individuale) e 📤 Uscita (macellato/morto/venduto/predato/smarrito)": "लॉट की हर इकाई पर 2 बटन: 🏷️ BDN (व्यक्तिगत पहचान संख्या देना) और 📤 निकासी (वध/मृत/बेचा/शिकार हुआ/खो गया)",
"Quando assegni un BDN a un suinetto del lotto, esce dal lotto ed entra nel Registro Suini con tutti i dati ereditati": "जब आप लॉट के किसी बच्चे को BDN देते हैं, तो वह लॉट से निकलकर सूअर रजिस्टर में अपने सारे डेटा के साथ आ जाता है",
"Quando tutti i suinetti hanno BDN o sono usciti, il lotto si chiude automaticamente": "जब सभी बच्चों को BDN मिल जाए या वे निकल जाएँ, तो लॉट अपने आप बंद हो जाता है",
"🧬 Genitori esterni nel form animale e parto": "🧬 पशु और ब्यांत फ़ॉर्म में बाहरी माता-पिता",
"Nel form animale e nel form parto, accanto al menu genitori aziendali, ora c'è un campo per inserire la matricola di un padre esterno (non registrato in azienda). Al salvataggio l'app crea automaticamente una scheda minima per quel padre esterno, con la razza scelta. Comparirà nel Pedigree e sarà disponibile per parti futuri.": "पशु फ़ॉर्म और ब्यांत फ़ॉर्म में, फ़ार्म के माता-पिता के मेनू के पास, अब बाहरी पिता (फ़ार्म पर दर्ज नहीं) की पहचान संख्या डालने का फ़ील्ड है। सहेजने पर ऐप उस बाहरी पिता का छोटा रिकॉर्ड चुनी गई नस्ल के साथ अपने आप बनाता है। वह वंशावली में दिखेगा और आगे के ब्यांतों के लिए उपलब्ध रहेगा।",
"🐾 Sezione UBA — Nuova": "🐾 पशु इकाई हिस्सा — नया",
"Calcolo delle Unità di Bestiame Adulto (UBA) per ogni animale con media ponderata secondo la fascia di età. Base per la ripartizione dei costi. Dati chiave:": "हर पशु के लिए वयस्क पशु इकाई (UBA) की गणना, उम्र के वर्ग के अनुसार भारित औसत के साथ। लागत बाँटने का आधार। मुख्य जानकारी:",
"UBA medio = coefficiente medio ponderato tra le fasce di età nel periodo di calcolo": "औसत पशु इकाई = गणना की अवधि में उम्र के वर्गों का भारित औसत गुणांक",
"Periodo di calcolo = MAX(nascita, 1° gennaio) → oggi (o data uscita)": "गणना की अवधि = MAX(जन्म, 1 जनवरी) → आज (या निकासी की तारीख)",
"UBA-giorni = UBA medio × giorni nel periodo (base per la ripartizione costi)": "पशु-इकाई-दिन = औसत पशु इकाई × अवधि के दिन (लागत बाँटने का आधार)",
"Data di riferimento configurabile (utile per bilanci parziali)": "संदर्भ तारीख बदली जा सकती है (बीच के हिसाब के लिए उपयोगी)",
"Filtri per specie (tutti / bovino / suino / ovino) e per stato (attivi / usciti / tutti)": "प्रजाति (सभी / गाय-बैल / सूअर / भेड़) और स्थिति (सक्रिय / निकले / सभी) के फ़िल्टर",
"🧬 Consanguineità — Nuova sezione nel Pedigree": "🧬 निकट-संबंधी प्रजनन — वंशावली में नया हिस्सा",
"Nella scheda animale del Pedigree c'è ora il tab 🚫 Consanguineità con elenco genitori/figli/fratelli": "वंशावली के पशु रिकॉर्ड में अब 🚫 निकट-संबंधी प्रजनन टैब है, माता-पिता/संतान/भाई-बहन की सूची के साथ",
"Report Excel con due fogli: Accoppiamenti a rischio (prevenzione monta) e Capi con genealogia consanguinea": "दो शीट वाली Excel रिपोर्ट: जोखिम वाले मिलन (मिलन की रोकथाम) और निकट-संबंधी वंश वाले पशु",
"Nell'elenco a schermo degli accoppiamenti a rischio, accanto a nome e matricola di maschio e femmina compare la RAZZA in evidenza — utile per capire subito se la coppia riguarda animali di razza pregiata": "स्क्रीन पर जोखिम वाले मिलन की सूची में नर और मादा के नाम और पहचान संख्या के पास नस्ल प्रमुखता से दिखती है — तुरंत समझने के लिए कि जोड़ा कीमती नस्ल का है या नहीं",
"🏷️ Data registrazione BDN — Nuovo campo": "🏷️ BDN पंजीकरण तारीख — नया फ़ील्ड",
"Ora ogni animale ha due date: data di nascita e data registrazione BDN (attribuzione ufficiale matricola). Compare nella scheda e nell'export.": "हर पशु की अब दो तारीखें हैं: जन्म तिथि और BDN पंजीकरण तिथि (आधिकारिक पहचान संख्या मिलने की)। यह रिकॉर्ड और निर्यात में दिखती है।",
"♀ Riproduttrice — Qualifica automatica": "♀ प्रजनक मादा — अपने आप योग्यता",
"Il toggle riproduttore/riproduttrice è ora disponibile anche per le femmine": "प्रजनक का स्विच अब मादाओं के लिए भी है",
"Alla registrazione di un parto, la madre viene marcata automaticamente come riproduttrice": "ब्यांत दर्ज होने पर माँ अपने आप प्रजनक मादा बन जाती है",
"Il Registro Riproduttori mostra sia maschi (♂) sia femmine (♀)": "प्रजनक रजिस्टर नर (♂) और मादा (♀) दोनों दिखाता है",
"🏆 Selezione Genetica — Nuovi indicatori": "🏆 आनुवंशिक चयन — नए संकेतक",
"Età al primo parto (mesi)": "पहले ब्यांत की उम्र (महीने)",
"Produttività annua stimata (figli/anno di carriera)": "अनुमानित सालाना उत्पादकता (प्रजनन के हर साल में संतानें)",
"🥩 Statistiche figli macellati: resa carcassa media, peso carcassa medio, IPG carcassa medio dei figli — indicatore genetico del valore del riproduttore per la resa": "🥩 वध की गई संतानों के आँकड़े: औसत शव उपज, औसत शव वज़न, संतानों की औसत रोज़ाना शव बढ़त — उपज के लिए प्रजनक के मूल्य का आनुवंशिक संकेतक",
"📈 IPG — Incremento Peso Giornaliero": "📈 रोज़ाना वज़न बढ़त",
"Calcolato automaticamente dove ci sono peso ingresso e peso uscita:": "जहाँ आगमन का वज़न और निकासी का वज़न हों, वहाँ अपने आप गणना:",
"IPG peso vivo (kg/gg) = peso_vivo_uscita / giorni_permanenza": "जीवित वज़न की रोज़ाना बढ़त (kg/दिन) = निकासी का जीवित वज़न / फ़ार्म पर दिन",
"IPG carcassa (kg/gg) = peso_carcassa / giorni_permanenza": "शव की रोज़ाना बढ़त (kg/दिन) = शव का वज़न / फ़ार्म पर दिन",
"Compare nella scheda animale uscito, nel Registro Uscite, e negli export Excel": "यह निकले पशु के रिकॉर्ड, निकासी रजिस्टर और Excel निर्यात में दिखती है",
"📤 Filtro Attivi / Usciti in tutte le sezioni": "📤 सभी हिस्सों में सक्रिय / निकले फ़िल्टर",
"Anagrafica, Pedigree e Selezione Genetica hanno un doppio filtro: specie + stato (Attivi / Usciti / Tutti). Default: solo Attivi. Nell'Export gli animali attivi e usciti sono in fogli separati.": "रजिस्टर, वंशावली और आनुवंशिक चयन में दोहरा फ़िल्टर है: प्रजाति + स्थिति (सक्रिय / निकले / सभी)। पहले से: केवल सक्रिय। निर्यात में सक्रिय और निकले पशु अलग शीट में होते हैं।",
"🐄 Nuova razza bovina: Limousine": "🐄 नई गाय नस्ल: Limousine",
"Aggiunta alle razze bovine disponibili sia nel form animale sia nel form padre esterno.": "पशु फ़ॉर्म और बाहरी पिता फ़ॉर्म दोनों में उपलब्ध गाय नस्लों में जोड़ी गई।",
"👥 Parti gemellari bovini e ovini": "👥 गाय और भेड़ में जुड़वाँ ब्यांत",
"Registrando un parto con più nati vivi, l'app apre un blocco per ogni gemello con matricola, sesso e peso individuali.": "कई ज़िंदा बच्चों वाला ब्यांत दर्ज करते समय ऐप हर जुड़वाँ के लिए अलग खाना खोलता है — पहचान संख्या, लिंग और वज़न के साथ।",
"Novità v65 → v119 (settembre 2026)": "नया v65 → v119 (सितंबर 2026)",
"🌾 Coltivazione: costi, report, storico e programma (v115 → v119)": "🌾 खेती: लागत, रिपोर्ट, इतिहास और योजना (v115 → v119)",
"Caricate le schede campo approvate dal 2019/2020 al 2025/2026 con i costi. Nuove linguette 📈 Report (costi, mercato, rese di riferimento ISTAT, semaforo, esportazione Excel, confronto tra stagioni), 📚 Storico (per coltura, per campo e tre classifiche) e 🗓️ Programma (semina e concimazione per campo, lista degli acquisti). Nella Semina il seme si sceglie da un elenco, con i semi del programma in cima. Balloni e rotoballe a 340 chilogrammi. Tutto descritto nella sezione Coltivazione di questa guida.": "2019/2020 से 2025/2026 तक के स्वीकृत खेत रिकॉर्ड लागत के साथ दर्ज किए गए। नए टैब 📈 रिपोर्ट (लागत, बाज़ार, ISTAT संदर्भ उपज, ट्रैफ़िक-लाइट, Excel निर्यात, मौसमों की तुलना), 📚 इतिहास (फ़सल के अनुसार, खेत के अनुसार और तीन रैंकिंग) और 🗓️ योजना (खेत के अनुसार बुवाई और खाद, खरीद सूची)। बुवाई में बीज सूची से चुना जाता है, योजना के बीज सबसे ऊपर। गट्ठर और गोल गट्ठर 340 किलोग्राम। सब कुछ इस मार्गदर्शिका के खेती हिस्से में बताया गया है।",
"🌾 Sezione Coltivazione — completamente nuova": "🌾 खेती हिस्सा — पूरी तरह नया",
"I 16 campi aziendali con foto aeree, catasto, colture per campagna, semine, le 15 lavorazioni ripetibili, raccolta per prodotto e riepilogo rese. Ha una sua sezione dedicata in questa guida.": "फ़ार्म के 16 खेत हवाई फ़ोटो, भूमि-रिकॉर्ड, मौसम के अनुसार फ़सलें, बुवाई, 15 दोहराए जा सकने वाले खेत के काम, उत्पाद के अनुसार कटाई और उपज सारांश के साथ। इस मार्गदर्शिका में इसका अपना हिस्सा है।",
"⚖️ Storico Pesate": "⚖️ वज़न का इतिहास",
"Nuovo tab nella scheda animale: ogni pesata è una riga, con tipo di rilevazione e distinzione fra peso reale e stimato. Sostituisce il vecchio campo unico che si sovrascriveva. Vedi la sezione Pesate.": "पशु रिकॉर्ड में नया टैब: हर वज़न एक पंक्ति है, माप के प्रकार और असली व अनुमानित वज़न के अंतर के साथ। यह पुराने एकल फ़ील्ड की जगह लेता है जो ऊपर लिखा जाता था। वज़न हिस्सा देखें।",
"♂ I maschi non nascono più riproduttori": "♂ नर अब जन्म से प्रजनक नहीं होते",
"Correzione importante: prima ogni maschio veniva marcato riproduttore automaticamente alla nascita. Ora lo diventa solo con l'attivazione esplicita del toggle, e viene registrata la data di qualifica. Le femmine restano automatiche al primo parto.": "ज़रूरी सुधार: पहले हर नर जन्म पर अपने आप प्रजनक बन जाता था। अब वह केवल स्विच चालू करने पर बनता है, और योग्यता की तारीख दर्ज होती है। मादाएँ पहले ब्यांत पर अपने आप बनती हैं।",
"💰 Costi nella scheda animale": "💰 पशु रिकॉर्ड में लागत",
"Nuovo tab 💰 Costi: mostra anno per anno i costi calcolati dalla Contabilità Industriale, con UBA-giorni, mantenimento, quota scaricata sui figli e cumulato. Sola lettura.": "नया 💰 लागत टैब: लागत लेखा द्वारा गणना की गई साल-दर-साल लागत दिखाता है, पशु-इकाई-दिन, रखरखाव, संतानों पर डाला गया हिस्सा और कुल जोड़ के साथ। केवल पढ़ने के लिए।",
"⚠️ Avviso costo di acquisto mancante": "⚠️ खरीद लागत न होने की चेतावनी",
"Badge rosso in Anagrafica e avviso nella scheda quando un animale acquistato non ha il prezzo. Lo stesso avviso compare nella Contabilità Industriale, ed è lo stesso campo: si compila da una parte e sparisce da entrambe.": "खरीदे गए पशु का मूल्य न हो तो रजिस्टर में लाल बैज और रिकॉर्ड में चेतावनी। यही चेतावनी लागत लेखा में भी दिखती है, और फ़ील्ड एक ही है: एक जगह भरें, दोनों जगह से हट जाती है।",
"📏 Peso all'ingresso": "📏 आगमन का वज़न",
"Nuovo campo accanto a peso nascita e peso attuale, per registrare quanto pesava l'animale quando è entrato in azienda. Serve soprattutto per gli acquistati, di cui il peso di nascita vero non si conosce.": "जन्म वज़न और वर्तमान वज़न के पास नया फ़ील्ड — पशु फ़ार्म पर आते समय कितना वज़नी था, यह दर्ज करने के लिए। खासकर खरीदे पशुओं के लिए, जिनका असली जन्म वज़न पता नहीं।",
"🐷 I costi seguono il suinetto quando prende il BDN": "🐷 BDN मिलने पर लागत सूअर के बच्चे के साथ जाती है",
"Quando assegni un BDN a un'unità di lotto, i costi che quella unità aveva già maturato mentre stava nel lotto vengono ricollegati alla nuova scheda animale, invece di ripartire da zero.": "जब आप लॉट की किसी इकाई को BDN देते हैं, तो लॉट में रहते हुए उसकी जमा हुई लागत नए पशु रिकॉर्ड से जुड़ जाती है, शून्य से शुरू नहीं होती।",
"📅 Giorni di vita nell'export": "📅 निर्यात में जीवन के दिन",
"Nuova colonna nell'export Excel degli animali, subito dopo Data uscita: i giorni fra nascita e uscita, che prima andavano calcolati a mano ogni volta.": "पशुओं के Excel निर्यात में निकासी की तारीख के ठीक बाद नया कॉलम: जन्म और निकासी के बीच के दिन, जो पहले हर बार हाथ से गिनने पड़ते थे।",
"🗺️ Barra dei moduli riordinata": "🗺️ मॉड्यूल पट्टी का नया क्रम",
"Tolte dalla barra 📊 Costi, 🧾 Origine e 🏭 Struttura, il cui lavoro è passato alla Contabilità Industriale. Aggiunta 🌾 Coltivazione. Nessun dato è stato cancellato.": "पट्टी से 📊 लागत, 🧾 उत्पत्ति और 🏭 ढाँचा हटाए गए, जिनका काम अब लागत लेखा में होता है। 🌾 खेती जोड़ी गई। कोई डेटा नहीं मिटाया गया।",
"🚫 Accoppiamenti a rischio ordinati per priorità genetica": "🚫 जोखिम वाले मिलन आनुवंशिक प्राथमिकता के क्रम में",
"Nel Report Consanguineità, dentro ogni specie, le coppie a rischio sono ora raggruppate per gravità genetica. Il meticcio non è una razza ma il risultato di un incrocio, quindi la consanguineità fra due soggetti della stessa razza pura pesa molto più che fra due meticci.": "निकट-संबंधी प्रजनन रिपोर्ट में हर प्रजाति के भीतर जोखिम वाले जोड़े अब आनुवंशिक गंभीरता के अनुसार समूहित हैं। संकर कोई नस्ल नहीं, बल्कि मेल का परिणाम है, इसलिए एक ही शुद्ध नस्ल के दो पशुओं के बीच निकट संबंध दो संकरों की तुलना में कहीं ज़्यादा गंभीर है।",
"1. Stessa razza": "1. एक ही नस्ल",
"I due animali sono della stessa razza pura — il caso più grave, si concentra la parentela dentro una linea di sangue di valore": "दोनों पशु एक ही शुद्ध नस्ल के हैं — सबसे गंभीर मामला, रिश्तेदारी एक कीमती वंश के अंदर इकट्ठी होती है",
"2. Razze pure diverse": "2. अलग शुद्ध नस्लें",
"Due razze pure differenti — comunque due soggetti di pregio": "दो अलग शुद्ध नस्लें — फिर भी दोनों कीमती पशु",
"3. Razza × meticcio": "3. नस्ल × संकर",
"Un animale di razza pura con un meticcio": "एक शुद्ध नस्ल का पशु एक संकर के साथ",
"4. Meticcio × meticcio": "4. संकर × संकर",
"Entrambi incroci — rilevanza genetica minore": "दोनों संकर — आनुवंशिक महत्व कम",
"5. Razza non indicata": "5. नस्ल नहीं बताई गई",
"Manca la razza su almeno uno dei due: va completata nella scheda": "दोनों में से कम से कम एक की नस्ल नहीं है: रिकॉर्ड में भरनी होगी",
"Lo stesso ordine si ritrova nel file Excel, sia in quello del pulsante 📊 Excel dentro il Report Consanguineità sia nel foglio 'Accoppiamenti a rischio' del modulo 📥 Esporta: le righe sono ordinate per specie e priorità, con due colonne in più (Priorità e Categoria) per poter filtrare.": "यही क्रम Excel फ़ाइल में भी है, निकट-संबंधी प्रजनन रिपोर्ट के 📊 Excel बटन वाली फ़ाइल में और 📥 निर्यात मॉड्यूल की 'जोखिम वाले मिलन' शीट में: पंक्तियाँ प्रजाति और प्राथमिकता के क्रम में हैं, फ़िल्टर करने के लिए दो अतिरिक्त कॉलम (प्राथमिकता और श्रेणी) के साथ।",
"🔢 Numero di versione nel menu": "🔢 मेनू में संस्करण संख्या",
"Toccando il proprio nome in alto a destra, sotto il ruolo compare ora la versione dell'app. Serve a capire in un attimo se un aggiornamento è arrivato davvero o se il browser sta mostrando una copia vecchia: in quel caso basta ricaricare con Ctrl+F5.": "ऊपर दाईं ओर अपना नाम दबाने पर भूमिका के नीचे अब ऐप का संस्करण दिखता है। इससे तुरंत पता चलता है कि अपडेट सच में आया या ब्राउज़र पुरानी कॉपी दिखा रहा है: ऐसे में Ctrl+F5 से दोबारा लोड करें।",
"Esportare dati in Excel": "डेटा Excel में निर्यात करना",
"Il tab 📥 Esporta permette di generare un file Excel su misura con solo i dati che ti servono.": "📥 निर्यात टैब से केवल ज़रूरी डेटा वाली अपनी Excel फ़ाइल बनाई जा सकती है।",
"Come funziona": "कैसे काम करता है",
"Vai in 📥 Esporta": "📥 निर्यात पर जाएँ",
"Imposta opzionalmente un filtro data (Da / A) — si applica a sanitario, alimentazione, parti, costi": "चाहें तो तारीख का फ़िल्टर लगाएँ (से / तक) — यह स्वास्थ्य, आहार, ब्यांत, लागत पर लागू होता है",
"Spunta le sezioni da includere (o usa 'Seleziona tutto')": "शामिल करने वाले हिस्सों पर टिक लगाएँ (या 'सब चुनें')",
"Tocca '📥 Genera Excel (N fogli)' — il file viene scaricato automaticamente": "'📥 Excel बनाएँ (N शीट)' दबाएँ — फ़ाइल अपने आप डाउनलोड होती है",
"Sezioni esportabili": "निर्यात होने वाले हिस्से",
"🐄 Anagrafica Bovini": "🐄 गाय-बैल रजिस्टर",
"Tutti i dati di ogni bovino: BDN, razza, pesi, provenienza, uscita, resa": "हर गाय-बैल का सारा डेटा: BDN, नस्ल, वज़न, उत्पत्ति, निकासी, उपज",
"🐷 Anagrafica Suini": "🐷 सूअर रजिस्टर",
"Come sopra per i suini con matricola": "ऊपर की तरह, पहचान संख्या वाले सूअरों के लिए",
"🐑 Anagrafica Ovini": "🐑 भेड़ रजिस्टर",
"Come sopra per gli ovini": "ऊपर की तरह, भेड़ों के लिए",
"Tutti gli animali usciti con giorni permanenza e resa macellazione": "सभी निकले पशु, फ़ार्म पर दिन और वध उपज के साथ",
"🐣 Parti": "🐣 ब्यांत",
"Registro completo parti per specie con padre, madre, nati": "प्रजाति के अनुसार ब्यांत का पूरा रजिस्टर — पिता, माता, बच्चों के साथ",
"💉 Sanitario": "💉 स्वास्थ्य",
"Tutti gli eventi sanitari inclusi i trattamenti su lotti suini": "सभी स्वास्थ्य घटनाएँ, सूअर लॉट पर इलाज सहित",
"🌾 Alimentazione": "🌾 आहार",
"Tutte le somministrazioni": "सभी खिलाने के रिकॉर्ड",
"📋 Lotti Riepilogo": "📋 लॉट सारांश",
"Un lotto per riga: vivi/macellati/deceduti/riproduttori/maschi/femmine": "हर पंक्ति में एक लॉट: ज़िंदा/वध/मृत/प्रजनक/नर/मादा",
"🏷️ Lotti Unità": "🏷️ लॉट इकाइयाँ",
"Una riga per ogni suinetto con tatuaggio, stato, pesi, resa": "हर सूअर के बच्चे की एक पंक्ति — टैटू, स्थिति, वज़न, उपज के साथ",
"🏆 KPI Selezione": "🏆 चयन संकेतक",
"IIP giorni e mesi, prolificità, % vivi per ogni fattrice": "हर प्रजनक मादा के लिए दिनों और महीनों में ब्यांत अंतराल, प्रजनन क्षमता, % ज़िंदा",
"🧾 Costi Animale": "🧾 पशु लागत",
"Costi per singolo animale": "हर पशु की लागत",
"📊 Costi Generali": "📊 सामान्य लागत",
"Costi fissi aziendali": "फ़ार्म की स्थिर लागत",
"🐄 Bovini attivi/usciti": "🐄 सक्रिय/निकले गाय-बैल",
"Fogli separati per attivi e usciti": "सक्रिय और निकले के लिए अलग शीट",
"🐷 Suini attivi/usciti": "🐷 सक्रिय/निकले सूअर",
"Come sopra": "ऊपर की तरह",
"🐑 Ovini attivi/usciti": "🐑 सक्रिय/निकली भेड़ें",
"🐾 UBA Riepilogo": "🐾 पशु इकाई सारांश",
"Aggregato UBA totali e UBA-giorni per specie e categoria": "प्रजाति और श्रेणी के अनुसार कुल पशु इकाई और पशु-इकाई-दिन",
"📋 UBA Dettaglio (tutti/bovini/ovini/suini)": "📋 पशु इकाई विवरण (सभी/गाय-बैल/भेड़/सूअर)",
"Dettaglio animali con UBA medio, UBA-giorni, categoria, stato": "औसत पशु इकाई, पशु-इकाई-दिन, श्रेणी, स्थिति के साथ पशुओं का विवरण",
"⚠️ Accoppiamenti a rischio": "⚠️ जोखिम वाले मिलन",
"Coppie maschio-femmina attive che sono consanguinee": "सक्रिय नर-मादा जोड़े जो आपस में रिश्तेदार हैं",
"🧬 Capi con genealogia consanguinea": "🧬 निकट-संबंधी वंश वाले पशु",
"Animali attivi nati da unioni consanguinee": "रिश्तेदार माता-पिता से जन्मे सक्रिय पशु",
"🏭 Macchinari": "🏭 मशीनें",
"Con quota annua, totale ammortizzato e valore residuo calcolati": "सालाना हिस्सा, कुल मूल्यह्रास और बचा मूल्य गणना के साथ",
"Il file Excel scaricato contiene un foglio separato per ogni sezione selezionata. Il nome del file include la data di export.": "डाउनलोड की गई Excel फ़ाइल में हर चुने हिस्से की अलग शीट होती है। फ़ाइल के नाम में निर्यात की तारीख होती है।",
"Guida per Allevatori": "पशुपालकों के लिए मार्गदर्शिका",
"App Allevamento": "फ़ार्म ऐप",
"Tutti i dati vengono salvati automaticamente nel database condiviso. Ogni operatore vede gli stessi dati in tempo reale da qualsiasi dispositivo.": "सारा डेटा साझा डेटाबेस में अपने आप सेव होता है। हर कर्मचारी किसी भी डिवाइस से एक ही डेटा तुरंत देखता है।",
"Caricamento...": "लोड हो रहा है...",
"Allevamento": "फ़ार्म",
"Ruolo": "भूमिका",
"Versione": "संस्करण",
"Lingua": "भाषा",
"Esporta tutto in Excel": "सब कुछ Excel में निर्यात करें",
"Guida per allevatori": "पशुपालकों के लिए मार्गदर्शिका",
"Esci": "लॉग आउट",
"Gestione": "प्रबंधन",
"Pedigree": "वंशावली",
"Lotti": "लॉट",
"Coltivazione": "खेती",
"Gasolio": "डीज़ल",
"Selezione": "चयन",
"Uscite": "निकासी",
"UBA": "पशु इकाई",
"Esporta": "निर्यात",
"Email": "ईमेल",
"Guida": "मार्गदर्शिका",
"Inserisci email e password": "ईमेल और पासवर्ड डालें",
"Credenziali non valide. Riprova.": "ईमेल या पासवर्ड गलत है। फिर कोशिश करें।",
"Compila tutti i campi": "सभी फ़ील्ड भरें",
"Password minimo 6 caratteri": "पासवर्ड कम से कम 6 अक्षर का हो",
"Registrazione completata! Controlla la tua email per confermare l'account.": "रजिस्ट्रेशन पूरा! खाते की पुष्टि के लिए अपना ईमेल देखें।",
"Gestione zootecnica integrata": "पशुपालन का पूरा प्रबंधन",
"Accedi": "लॉग इन",
"Registrati": "रजिस्टर करें",
"Nome e cognome": "नाम और उपनाम",
"Password": "पासवर्ड",
"Crea account": "खाता बनाएँ",
"Non hai un account?": "खाता नहीं है?"
};
export default D;
